# Generated by Django 5.0.1 on 2026-06-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='Символ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Старый курс')),
                ('new_rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Новый курс')),
                ('operation_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=10, verbose_name='Тип операции')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'История изменений курса',
                'verbose_name_plural': 'История изменений курсов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс')),
                ('operation_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=10, verbose_name='Тип операции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий курс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
            ],
            options={
                'verbose_name': 'Курс обмена',
                'verbose_name_plural': 'Курсы обмена',
                'ordering': ['-created_at'],
            },
        ),
    ]
