# Generated by Django 5.0.1 on 2026-06-16 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyratehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='currencyratehistory',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='base_currency',
            field=models.ForeignKey(limit_choices_to={'code': 'KGS'}, on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='currencies.currency', verbose_name='Базовая валюта'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rates', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='currencies.currency', verbose_name='Валюта'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency', 'operation_type', 'is_active'], name='currencies__currenc_c48365_idx'),
        ),
    ]
