# Generated by Django 5.0.1 on 2026-06-16 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='base_currency',
            field=models.ForeignKey(blank=True, limit_choices_to={'code': 'KGS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='currencies.currency', verbose_name='Базовая валюта'),
        ),
    ]
