# Generated by Django 5.0.1 on 2026-06-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('cancel', 'Отмена'), ('print', 'Печать'), ('export', 'Экспорт'), ('change_rate', 'Изменение курса'), ('deposit', 'Внесение'), ('withdrawal', 'Изъятие')], max_length=50, verbose_name='Действие')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='Устройство')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Лог аудита',
                'verbose_name_plural': 'Логи аудита',
                'ordering': ['-timestamp'],
            },
        ),
    ]
