# Generated by Django 6.0.6 on 2026-06-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, verbose_name='Платформа')),
                ('version', models.CharField(help_text='Например: 1.1.0', max_length=20, verbose_name='Версия')),
                ('build_number', models.IntegerField(default=1, verbose_name='Номер сборки')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное обновление')),
                ('update_url', models.URLField(blank=True, verbose_name='Ссылка на обновление')),
                ('changelog', models.TextField(blank=True, verbose_name='Список изменений')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Версия приложения',
                'verbose_name_plural': 'Версии приложений',
                'ordering': ['-created_at'],
                'unique_together': {('platform', 'version')},
            },
        ),
    ]
