# Generated by Django 6.0.6 on 2026-06-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appversion',
            unique_together={('platform', 'build_number')},
        ),
    ]
