# Generated by Django 5.1.15 on 2026-07-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_appversion_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("update", "Обновление приложения"),
                            ("news", "Новость"),
                            ("new_feature", "Новая функция"),
                            ("maintenance", "Технические работы"),
                            ("info", "Информационное сообщение"),
                            ("banner", "Баннер"),
                        ],
                        default="info",
                        max_length=30,
                        verbose_name="Тип уведомления",
                    ),
                ),
                (
                    "display_format",
                    models.CharField(
                        choices=[
                            ("full_screen", "Полноэкранный"),
                            ("modal", "Модальное окно"),
                            ("bottom_sheet", "Нижняя карточка"),
                            ("banner", "Баннер"),
                            ("card", "Карточка"),
                        ],
                        default="modal",
                        max_length=30,
                        verbose_name="Формат отображения",
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        help_text="Версия, к которой относится уведомление (например: 1.4.0)",
                        max_length=20,
                        verbose_name="Версия приложения",
                    ),
                ),
                (
                    "min_version",
                    models.CharField(
                        blank=True,
                        help_text="Минимально поддерживаемая версия",
                        max_length=20,
                        verbose_name="Минимальная версия",
                    ),
                ),
                (
                    "latest_version",
                    models.CharField(
                        blank=True,
                        help_text="Последняя доступная версия",
                        max_length=20,
                        verbose_name="Последняя версия",
                    ),
                ),
                (
                    "force_update",
                    models.BooleanField(
                        default=False, verbose_name="Обязательное обновление"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, verbose_name="URL изображения"),
                ),
                ("button_url", models.URLField(blank=True, verbose_name="URL кнопки")),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Текст кнопки"
                    ),
                ),
                (
                    "changelog",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Каждый пункт — отдельная строка",
                        verbose_name="Список изменений",
                    ),
                ),
                ("publish_at", models.DateTimeField(verbose_name="Дата публикации")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания действия"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликовано"),
                            ("archived", "Архив"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус публикации",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                            ("desktop", "Desktop"),
                            ("all", "Все"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Платформа",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        help_text="Роль пользователя или пусто для всех",
                        max_length=100,
                        verbose_name="Целевая аудитория",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Чем выше число, тем выше приоритет",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Просмотры"
                    ),
                ),
                (
                    "click_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Переходы по кнопке"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-priority", "-publish_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "publish_at"],
                        name="notificatio_status_8a2cf8_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_f2898f_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="notificatio_priorit_bf8ea0_idx"
                    ),
                ],
            },
        ),
    ]
