# Generated by Django 5.1.15 on 2026-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Отображается под заголовком в баннере",
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Открывается при нажатии на баннер",
                        verbose_name="Полный текст",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, verbose_name="URL изображения"),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text='URL для кнопки "Подробнее"',
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        default="Подробнее",
                        max_length=100,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Чем выше число, тем левее в карусели",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-priority", "-published_at"],
            },
        ),
    ]
