# Generated by Django 5.0.1 on 2026-06-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Номер операции')),
                ('operation_type', models.CharField(choices=[('buy', 'Покупка валюты'), ('sell', 'Продажа валюты')], max_length=20, verbose_name='Тип операции')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена'), ('partially_cancelled', 'Частично отменена')], default='active', max_length=20, verbose_name='Статус')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Имя клиента')),
                ('client_company', models.CharField(blank=True, max_length=200, verbose_name='Компания клиента')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс обмена')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма валюты')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая сумма (KGS)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отмены')),
                ('cancellation_type', models.CharField(choices=[('full', 'Полная отмена'), ('partial', 'Частичная отмена')], max_length=20, verbose_name='Тип отмены')),
                ('cancel_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма отмены')),
                ('reason', models.TextField(verbose_name='Причина отмены')),
            ],
            options={
                'verbose_name': 'Отмена операции',
                'verbose_name_plural': 'Отмены операций',
                'ordering': ['-cancelled_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата редактирования')),
                ('field_changed', models.CharField(max_length=100, verbose_name='Изменённое поле')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к изменению')),
            ],
            options={
                'verbose_name': 'История редактирования операции',
                'verbose_name_plural': 'История редактирования операций',
                'ordering': ['-edited_at'],
            },
        ),
    ]
