# Generated by Django 5.0.1 on 2026-06-16 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0002_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='Кассир'),
        ),
        migrations.AddField(
            model_name='operation',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='currencies.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='operationcancellation',
            name='cancelled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отменил'),
        ),
        migrations.AddField(
            model_name='operationcancellation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='operations.operation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='operationedithistory',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Редактировал'),
        ),
        migrations.AddField(
            model_name='operationedithistory',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='operations.operation', verbose_name='Операция'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['-created_at'], name='operations__created_e1715f_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['operation_number'], name='operations__operati_7993de_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['cashier', '-created_at'], name='operations__cashier_f8b742_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status', '-created_at'], name='operations__status_49ff68_idx'),
        ),
    ]
