/// Localized strings for the app.
/// Keys are the same across languages; values are the translations.
class AppStrings {
  const AppStrings._();

  /// All supported locales.
  static const List<String> supportedLocales = [
    'ru',
    'ky',
    'en',
    'uz',
    'uz_Cyrl',
  ];
  static const String defaultLocale = 'ru';

  /// Map of locale -> (string key -> translated value).
  static const Map<String, Map<String, String>> _strings = {
    'ru': _ru,
    'ky': _kg,
    'en': _en,
    'uz': _uz,
    'uz_Cyrl': _uzCyrillic,
  };

  /// Returns the translated string for [key] in [locale].
  /// Falls back to Russian, then to the key itself.
  static String t(String key, {String locale = 'ru'}) {
    return _strings[locale]?[key] ?? _strings['ru']?[key] ?? key;
  }

  /// Convenience: get all key-value pairs for a locale.
  static Map<String, String> forLocale(String locale) {
    return _strings[locale] ?? _strings['ru']!;
  }

  
  static const Map<String, String> _ru = {
    
    'app_name': 'My Exchange',
    'app_title': 'Моя волюта',

    
    'nav_operations': 'Операции',
    'nav_cash': 'Касса',
    'nav_currencies': 'Валюты',
    'nav_analytics': 'Аналитика',
    'nav_settings': 'Профиль',

    
    'login_title': 'Вход в систему',
    'login_username': 'Имя пользователя',
    'login_password': 'Пароль',
    'login_button': 'Войти',
    'login_error': 'Ошибка входа',
    'login_username_required': 'Введите имя пользователя',
    'login_password_required': 'Введите пароль',
    'login_password_min': 'Пароль должен быть не менее 6 символов',
    'login_version': 'Версия',
    'login_biometric': 'Войти по Touch ID / Face ID',
    'login_biometric_error': 'Биометрическая аутентификация недоступна',
    'login_biometric_failed': 'Не удалось выполнить вход по биометрии',
    'login_biometric_save': 'Запомнить для быстрого входа',
    'login_biometric_reason': 'Подтвердите личность для входа в приложение',

    
    'settings_title': 'Профиль и настройки',
    'settings_profile': 'Профиль',
    'settings_user_info': 'Информация о пользователе',
    'settings_role': 'Должность',
    'settings_email': 'Email',
    'settings_phone': 'Телефон',
    'settings_language': 'Язык',
    'settings_language_ru': 'Русский',
    'settings_language_kg': 'Кыргызча',
    'settings_language_en': 'English',
    'settings_language_uz': "O'zbekcha",
    'settings_language_uzCyrillic': 'Ўзбекча',
    'settings_app_version': 'Версия приложения',
    'settings_logout': 'Выйти',
    'settings_logout_confirm': 'Вы уверены, что хотите выйти?',
    'settings_logout_confirm_desc':
        'Для повторного входа потребуется ввести логин и пароль.',
    'settings_cancel': 'Отмена',
    'settings_confirm': 'Да, выйти',
    'settings_privacy_policy': 'Политика конфиденциальности',
    'settings_contact_support': 'Связаться с поддержкой',
    'settings_delete_account': 'Запросить удаление аккаунта',
    'settings_delete_account_desc':
        'Отправить запрос на удаление вашего аккаунта и всех связанных данных.',
    'settings_delete_account_confirm':
        'Запрос отправлен. С вами свяжутся в ближайшее время.',
    'settings_theme': 'Тема оформления',
    'settings_theme_light': 'Светлая',
    'settings_theme_dark': 'Тёмная',
    'settings_pin_code': 'PIN-код',
    'settings_pin_code_desc': 'Установить PIN-код для входа в приложение',
    'settings_biometric_login': 'Вход по биометрии',
    'settings_biometric_login_desc':
        'Использовать Touch ID / Face ID для быстрого входа',

    
    'lock_title': 'Введите PIN-код',
    'lock_subtitle': 'Введите PIN-код для разблокировки приложения',
    'lock_biometric': 'Touch ID / Face ID',
    'lock_biometric_reason': 'Подтвердите личность для входа в приложение',
    'lock_biometric_failed': 'Ошибка биометрии. Введите PIN-код',
    'lock_or': 'или',

    'settings_support_email': 'salievyt@gmail.com',
    'settings_support_chat': 'WhatsApp, Telegram',
    'settings_support_title': 'Связаться с поддержкой',
    'settings_support_description': 'Выберите удобный способ связи',
    'settings_privacy_note': 'Нажимая «Выйти», вы завершаете текущую сессию.',

    
    'operations_title': 'Операции',
    'operations_create': 'Операция',
    'operations_empty': 'Нет операций',
    'operations_load': 'Загрузить',
    'operations_today': 'Сегодня',
    'operations_buys': 'Покупки',
    'operations_sells': 'Продажи',
    'operations_buy': 'Покупка',
    'operations_sell': 'Продажа',
    'operations_search': 'Поиск по номеру, клиенту...',
    'operations_search_hint': 'Номер операции, имя клиента',
    'operations_filter_type': 'Тип',
    'operations_filter_all': 'Все',
    'operations_filter_period': 'Период',
    'operations_filter_period_today': 'Сегодня',
    'operations_filter_period_week': 'Неделя',
    'operations_filter_period_month': 'Месяц',
    'operations_filter_period_custom': 'Свой период',
    'operations_filter_period_all': 'Всё время',
    'operations_filter_sort': 'Сортировка',
    'operations_filter_currency': 'Валюта',
    'operations_filter_currency_all': 'Все валюты',
    'operations_columns': 'Колонки',
    'operations_columns_1': '1 колонка',
    'operations_columns_2': '2 колонки',
    'operations_filter_date_from': 'От',
    'operations_filter_date_to': 'До',
    'operations_filter_date_apply': 'Применить',
    'operations_edit': 'Редактировать',
    'operations_save': 'Сохранить',
    'operations_edit_title': 'Редактирование операции',
    'operations_edit_success': 'Операция обновлена',
    'operations_rate': 'Курс обмена',
    'operations_total': 'Итого к выдаче',
    'operations_amount': 'Сумма валюты',
    'operations_filter_sort_newest': 'Новые',
    'operations_filter_sort_oldest': 'Старые',
    'operations_filter_sort_amount_asc': 'Сумма ↑',
    'operations_filter_sort_amount_desc': 'Сумма ↓',
    'operations_clear_filters': 'Сбросить фильтры',
    'operations_found': 'Найдено:',

    
    'cash_title': 'Касса',
    'cash_balances': 'Остатки',
    'cash_register_open': 'Смена открыта',
    'cash_register_closed': 'Смена не открыта',
    'cash_register_open_desc': 'Откройте смену для начала работы',
    'cash_register_close': 'Закрыть смену',
    'cash_open_shift': 'Открыть смену',
    'cash_transaction': 'Транзакция',
    'cash_available': 'Доступно',
    'cash_reserved': 'Зарезервировано',
    'cash_avg_rate': 'Ср. курс',
    'cash_cashier': 'Кассир',
    'cash_opened_at': 'Открыта',
    'cash_opening_balance': 'Начальные остатки',
    'cash_no_data': 'Нет данных',

    
    'currencies_title': 'Валюты',
    'currencies_buy': 'Покупка',
    'currencies_sell': 'Продажа',

    
    'analytics_title': 'Аналитика',
    'analytics_no_data': 'Нет данных для отображения',
    'analytics_no_data_desc': 'Статистика появится после совершения операций',
    'analytics_overall': 'Общая статистика',
    'analytics_operations_today': 'Операций сегодня',
    'analytics_buys_sells': 'Покупок / Продаж',
    'analytics_turnover': 'Оборот (сом)',
    'analytics_clients': 'Клиентов',
    'analytics_rates': 'Курсы валют',
    'analytics_daily_chart': 'Операции по дням',
    'analytics_popular_currencies': 'Популярные валюты',
    'analytics_profitability': 'Рентабельность (маржа %)',
    'analytics_cashiers': 'Кассиры',
    'analytics_cash_balances': 'Остатки в кассе',
    'analytics_reports': 'Отчёты',

    
    'reports_title': 'Отчёты',
    'reports_subtitle': 'Скачать отчёты',
    'reports_desc':
        'Экспорт данных в формате CSV, Excel или PDF по нажатию одной кнопки',
    'reports_daily': 'Дневной отчёт',
    'reports_daily_desc': 'Итоги дня: операции, оборот, остатки',
    'reports_monthly': 'Месячный отчёт',
    'reports_monthly_desc': 'Статистика за месяц по дням',
    'reports_operations': 'Экспорт операций',
    'reports_operations_desc': 'Все операции за период в таблице',
    'reports_cash': 'Экспорт кассы',
    'reports_cash_desc': 'Движение денег по кассе',
    'reports_download': 'Скачать',
    'reports_generating': 'Формирование отчёта...',
    'reports_saved': 'Файл сохранён',
    'reports_saved_desc':
        'Файл готов к использованию. Нажмите «Поделиться», чтобы отправить или сохранить его.',
    'reports_open_share': 'Поделиться / Сохранить',

    
    'general_retry': 'Повторить',
    'general_refresh': 'Обновить',
    'general_loading': 'Загрузка...',
    'general_error': 'Ошибка',
    'general_success': 'Успешно',
    'general_close': 'Закрыть',
    'general_ops': 'оп.',
    'general_today': 'Сегодня',
    'general_yesterday': 'Вчера',
    'general_just_now': 'Только что',
    'general_min_ago': 'мин. назад',
    'general_hours_ago': 'ч. назад',
    'general_days_ago': 'дн. назад',
    'general_som': 'сом',

    
    'error_retry': 'Повторить',
    'error_close': 'Закрыть',
    'footer_made_with_love': 'Сделано с любовью',

    
    'update_available': 'Доступно обновление',
    'update_version': 'Версия {version}',
    'update_required': 'Обязательное обновление',
    'update_whats_new': 'Что нового:',
    'update_link': 'Ссылка для обновления: {url}',
    'update_now': 'Обновить сейчас',
    'update_later': 'Позже',

    
    'lock_wrong_pin': 'Неверный PIN-код',

    
    'operation_card_cancel': 'Отменить',
    'operation_card_edit': 'Править',
    'operation_card_rate': 'Курс: {rate}',
    'operation_card_total': 'Итого: {amount}',

    
    'operation_detail_edit_tooltip': 'Редактировать',
    'operation_detail_amount': 'Сумма операции',
    'operation_detail_rate_label': 'Курс',
    'operation_detail_total_som': 'Итого в сомах',
    'operation_detail_client': 'Клиент',
    'operation_detail_client_name': 'Имя',
    'operation_detail_client_company': 'Компания',
    'operation_detail_details': 'Детали',
    'operation_detail_cashier': 'Кассир',
    'operation_detail_created': 'Дата создания',
    'operation_detail_updated': 'Последнее изменение',
    'operation_detail_id': 'ID операции',
    'operation_detail_comment': 'Комментарий',
    'operation_detail_edit_button': 'Редактировать операцию',
    'operation_detail_status': 'Статус',
    'operation_detail_status_created': 'Операция создана',
    'operation_detail_status_created_sub': 'Проведена в системе',
    'operation_detail_status_executed': 'Исполнена',
    'operation_detail_status_cancelled': 'Отменена',
    'operation_detail_status_partial': 'Частично отменена',
    'operation_detail_status_executed_sub': 'Операция завершена успешно',
    'operation_detail_status_cancelled_sub': 'Операция отменена',
    'operation_detail_status_partial_sub': 'Часть операции отменена',

    
    'create_operation_select_currency': 'Выберите валюту',
    'create_operation_insufficient_kgs': 'Недостаточно сом (KGS) в кассе. Доступно: {balance}, требуется: {required}',
    'create_operation_insufficient_currency': 'Недостаточно {currency} в кассе. Доступно: {balance}',
    'create_operation_success_updated': 'Операция обновлена',
    'create_operation_error_update': 'Ошибка обновления операции',
    'create_operation_success_created': 'Операция успешно создана',
    'create_operation_error_create': 'Ошибка создания операции',
    'create_operation_title_edit': 'Редактирование операции',
    'create_operation_title_new': 'Новая операция',
    'create_operation_type': 'Тип операции',
    'create_operation_currency': 'Валюта',
    'create_operation_currency_select': 'Выберите валюту',
    'create_operation_params': 'Параметры операции',
    'create_operation_params_hint': 'Изменение любых двух полей автоматически пересчитывает третье',
    'create_operation_amount_buy_label': 'Сумма покупки (валюта)',
    'create_operation_amount_sell_label': 'Сумма продажи (валюта)',
    'create_operation_amount_required': 'Введите сумму',
    'create_operation_amount_invalid': 'Некорректная сумма',
    'create_operation_rate_label': 'Курс обмена',
    'create_operation_rate_required': 'Введите курс',
    'create_operation_rate_invalid': 'Некорректный курс',
    'create_operation_total_label': 'Итого к выдаче (сом)',
    'create_operation_total_required': 'Введите итоговую сумму',
    'create_operation_total_invalid': 'Некорректная сумма',
    'create_operation_summary_amount': 'Сумма',
    'create_operation_summary_rate': 'Курс',
    'create_operation_summary_total': 'Итого',
    'create_operation_client_info': 'Информация о клиенте',
    'create_operation_client_name': 'Имя клиента (необязательно)',
    'create_operation_client_company': 'Компания (необязательно)',
    'create_operation_comment_label': 'Комментарий',
    'create_operation_comment_optional': 'Комментарий (необязательно)',
    'create_operation_save': 'Сохранить изменения',
    'create_operation_create': 'Создать операцию',

    
    'operations_filter_empty': 'Попробуйте изменить параметры фильтрации',
    'operations_empty_action': 'Нажмите кнопку ниже, чтобы создать первую операцию',
    'operations_cancel_title': 'Отмена операции',
    'operations_cancel_confirm': 'Отменить операцию №{number}?',
    'operations_cancel_button': 'Отмена',
    'operations_cancel_confirm_button': 'Подтвердить отмену',
    'operations_cancel_success': 'Операция отменена',
    'operations_cancel_error': 'Ошибка отмены операции',
    'operations_no_results': 'Нет операций',
    'operations_filter_currency_title': 'Фильтр по валюте',

    
    'cash_no_balances': 'Нет балансов',
    'cash_no_balances_desc': 'Балансы появятся после открытия смены и совершения первых операций',

    
    'close_register_success': 'Смена успешно закрыта',
    'close_register_error': 'Ошибка закрытия смены',
    'close_register_title': 'Закрытие смены',
    'close_register_loading': 'Итоги дня загружаются...',
    'close_register_summary': 'Итоги дня',
    'close_register_total_ops': 'Всего операций',
    'close_register_buys': 'Покупок',
    'close_register_sells': 'Продаж',
    'close_register_turnover': 'Оборот: {amount}',
    'close_register_cancelled': 'Отмен: {count}',
    'close_register_enter_balances': 'Внесите фактические остатки по валютам',
    'close_register_required': 'Обязательное поле',
    'close_register_invalid': 'Некорректная сумма',
    'close_register_comment': 'Комментарий (необязательно)',
    'close_register_cancel': 'Отмена',
    'close_register_confirm': 'Закрыть смену',

    
    'open_register_need_balance': 'Введите хотя бы один остаток',
    'open_register_success': 'Смена успешно открыта',
    'open_register_error': 'Ошибка открытия смены',
    'open_register_title': 'Открытие смены',
    'open_register_hint': 'Внесите начальные остатки по валютам',
    'open_register_invalid': 'Некорректная сумма',
    'open_register_comment': 'Комментарий (необязательно)',
    'open_register_cancel': 'Отмена',
    'open_register_confirm': 'Открыть смену',

    
    'transaction_select_currency': 'Выберите валюту',
    'transaction_success': 'Транзакция успешно создана',
    'transaction_error': 'Ошибка создания транзакции',
    'transaction_title': 'Транзакция',
    'transaction_deposit': 'Внесение',
    'transaction_withdrawal': 'Выдача',
    'transaction_currency': 'Валюта',
    'transaction_currency_placeholder': 'Выберите валюту',
    'transaction_amount': 'Сумма',
    'transaction_amount_required': 'Введите сумму',
    'transaction_amount_invalid': 'Некорректная сумма',
    'transaction_client_name': 'Клиент (необязательно)',
    'transaction_client_company': 'Наименование компании (необязательно)',
    'transaction_rate': 'Курс (если иностранная валюта)',
    'transaction_rate_hint': 'Необязательно',
    'transaction_comment': 'Комментарий (необязательно)',
    'transaction_cancel': 'Отмена',
    'transaction_create': 'Создать',

    
    'currencies_empty': 'Курсы валют появятся после загрузки данных',
    'currencies_total': 'Всего',
    'currencies_active': 'Активных',
    'currencies_with_rates': 'С курсами',
    'currencies_edit_rates': 'Редактирование курсов',
    'currencies_active_status': 'Активна',
    'currencies_inactive_status': 'Неактивна',
    'currencies_no_rates': 'Курсы не установлены',
    'currencies_no_rates_short': 'Курсы не указаны',
    'currencies_rate_required': 'Введите курс',
    'currencies_rate_invalid': 'Неверное число',

    
    'analytics_operations': 'Операций',
    'analytics_turnover_short': 'Оборот',
    'analytics_buys_sells_short': 'Покупок/Продаж',
    'analytics_clients_short': 'Клиентов',
    'analytics_operations_today_short': 'Операций сегодня',
    'analytics_turnover_today': 'Оборот сегодня',
    'analytics_buys_sells_today': 'Покупок / Продаж',
    'analytics_clients_today': 'Клиентов',
    'analytics_period_7d': '7 дней',
    'analytics_period_14d': '14 дней',
    'analytics_period_30d': '30 дней',
    'analytics_ops_count': '{count} оп.',
    'analytics_available': 'Доступно: {balance}',

    
    'charts_no_data_period': 'Нет данных за период',
    'charts_tooltip_buy_sell': 'Покупка: {buy} • Продажа: {sell}',
    'charts_no_data': 'Нет данных',
    'charts_ops_turnover': 'Операций: {ops}\nОборот: {turnover}',
    'charts_no_profitability': 'Нет данных о рентабельности',
    'charts_profit': 'Прибыль: {spread}\nМаржа: {margin}%',

    
    'reports_cashier_shift': 'Отчёт по смене кассира',
    'reports_cashier_shift_desc': 'PDF-отчёт: остатки, операции, итоги смены',

    
    'settings_pin_6_digits': 'PIN-код должен быть 6 цифр',
    'settings_pin_mismatch': 'PIN-коды не совпадают',
    'settings_pin_set': 'PIN-код установлен',
    'settings_pin_removed': 'PIN-код удалён',
    'settings_pin_new': 'Новый PIN-код',
    'settings_pin_confirm': 'Подтвердите PIN-код',
    'settings_pin_delete': 'Удалить PIN',
    'settings_pin_save': 'Сохранить',
    'settings_support_message': 'Здравствуйте! Мне нужна помощь с приложением My Exchange.',

    
    'entity_operation_type_buy': 'Покупка',
    'entity_operation_type_sell': 'Продажа',
    'entity_operation_status_active': 'Активна',
    'entity_operation_status_cancelled': 'Отменена',
    'entity_operation_status_partial': 'Частично отменена',
    'entity_user_role_cashier': 'Кассир',
    'entity_user_role_senior_cashier': 'Старший кассир',
    'entity_user_role_admin': 'Администратор',
    'entity_transaction_type_deposit': 'Внесение наличности',
    'entity_transaction_type_withdrawal': 'Выдача наличности',
    'entity_transaction_type_inkassation': 'Инкассация',

    
    'onboarding_skip': 'Пропустить',
    'onboarding_next': 'Далее',
    'onboarding_get_started': 'Начать работу',
    'onboarding_welcome_title': 'Добро пожаловать в My Exchange',
    'onboarding_welcome_desc': 'Управляйте обменными операциями быстро и эффективно. Следите за курсами валют, ведите кассу и анализируйте прибыль.',
    'onboarding_operations_title': 'Операции и касса',
    'onboarding_operations_desc': 'Создавайте операции покупки и продажи валют, управляйте кассовыми сменами и отслеживайте движение денег в реальном времени.',
    'onboarding_analytics_title': 'Аналитика и отчёты',
    'onboarding_analytics_desc': 'Отслеживайте прибыль, популярность валют и загружайте детальные отчёты в один клик.',
  };

  
  static const Map<String, String> _kg = {
    
    'app_name': 'My Exchange',
    'app_title': 'Моя волюта',

    
    'nav_operations': 'Операциялар',
    'nav_cash': 'Касса',
    'nav_currencies': 'Валюталар',
    'nav_analytics': 'Аналитика',
    'nav_settings': 'Профиль',

    
    'login_title': 'Системага кирүү',
    'login_username': 'Колдонуучу аты',
    'login_password': 'Сырсөз',
    'login_button': 'Кирүү',
    'login_error': 'Кирүү катасы',
    'login_username_required': 'Колдонуучу атын жазыңыз',
    'login_password_required': 'Сырсөздү жазыңыз',
    'login_password_min': 'Сырсөз кеминде 6 символ болушу керек',
    'login_version': 'Версия',
    'login_biometric': 'Touch ID / Face ID аркылуу кирүү',
    'login_biometric_error': 'Биометриялык аутентификация жеткиликтүү эмес',
    'login_biometric_failed': 'Биометрия аркылуу кирүү мүмкүн болгон жок',
    'login_biometric_save': 'Тез кирүү үчүн сактоо',
    'login_biometric_reason': 'Кирүү үчүн инсандыгыңызды тастыктаңыз',

    
    'settings_title': 'Профиль жана орнотуулар',
    'settings_profile': 'Профиль',
    'settings_user_info': 'Колдонуучу маалыматы',
    'settings_role': 'Кызматы',
    'settings_email': 'Email',
    'settings_phone': 'Телефон',
    'settings_language': 'Тил',
    'settings_language_ru': 'Орусча',
    'settings_language_kg': 'Кыргызча',
    'settings_language_en': 'English',
    'settings_language_uz': "O'zbekcha",
    'settings_language_uzCyrillic': 'Ўзбекча',
    'settings_app_version': 'Колдонмо версиясы',
    'settings_logout': 'Чыгуу',
    'settings_logout_confirm': 'Чыгууга ишенесизби?',
    'settings_logout_confirm_desc':
        'Кайра кирүү үчүн логин жана сырсөз керек болот.',
    'settings_cancel': 'Жокко чыгаруу',
    'settings_confirm': 'Ооба, чыгуу',
    'settings_privacy_policy': 'Купуялык саясаты',
    'settings_contact_support': 'Колдоо кызматы',
    'settings_delete_account': 'Аккаунтту жок кылуу',
    'settings_delete_account_desc':
        'Аккаунтуңузду жана бардык маалыматтарды жок кылуу өтүнүчүн жөнөтүү.',
    'settings_delete_account_confirm':
        'Өтүнүч жөнөтүлдү. Жакында сиз менен байланышабыз.',
    'settings_theme': 'Тема',
    'settings_theme_light': 'Жарык',
    'settings_theme_dark': 'Караңгы',
    'settings_pin_code': 'PIN-код',
    'settings_pin_code_desc': 'Колдонмого кирүү үчүн PIN-код орнотуу',
    'settings_biometric_login': 'Биометриялык кирүү',
    'settings_biometric_login_desc':
        'Тез кирүү үчүн Touch ID / Face ID колдонуу',
    'lock_title': 'PIN-кодду киргизиңиз',
    'lock_subtitle': 'Колдонмону ачуу үчүн PIN-кодду киргизиңиз',
    'lock_biometric': 'Touch ID / Face ID',
    'lock_biometric_reason': 'Кирүү үчүн инсандыгыңызды тастыктаңыз',
    'lock_biometric_failed': 'Биометрия катасы. PIN-кодду киргизиңиз',
    'lock_or': 'же',
    'settings_support_email': 'salievyt@gmail.com',
    'settings_support_chat': 'WhatsApp, Telegram',
    'settings_support_title': 'Колдоо кызматы менен байланышуу',
    'settings_support_description': 'Байланышуу үчүн ыңгайлуу ыкманы тандаңыз',
    'settings_privacy_note':
        '«Чыгуу» баскычын басуу менен, сиз учурдагы сессияны аяктайсыз.',

    
    'operations_title': 'Операциялар',
    'operations_create': 'Операция',
    'operations_empty': 'Операциялар жок',
    'operations_load': 'Жүктөө',
    'operations_today': 'Бүгүн',
    'operations_buys': 'Сатып алуулар',
    'operations_sells': 'Сатуулар',
    'operations_buy': 'Сатып алуу',
    'operations_sell': 'Сатуу',
    'operations_search': 'Номери, кардар аты боюнча издөө...',
    'operations_search_hint': 'Операция номери, кардардын аты',
    'operations_filter_type': 'Түрү',
    'operations_filter_all': 'Баары',
    'operations_filter_period': 'Мөөнөт',
    'operations_filter_period_today': 'Бүгүн',
    'operations_filter_period_week': 'Апта',
    'operations_filter_period_month': 'Ай',
    'operations_filter_period_all': 'Бардык убакыт',
    'operations_filter_sort': 'Иреттөө',
    'operations_filter_period_custom': 'Өз мөөнөтү',
    'operations_filter_currency': 'Валюта',
    'operations_filter_currency_all': 'Бардык валюталар',
    'operations_columns': 'Колонкалар',
    'operations_columns_1': '1 колонка',
    'operations_columns_2': '2 колонка',
    'operations_filter_date_from': 'Башталган күн',
    'operations_filter_date_to': 'Чейинки күн',
    'operations_filter_date_apply': 'Колдонуу',
    'operations_edit': 'Оңдоо',
    'operations_save': 'Сактоо',
    'operations_edit_title': 'Операцияны оңдоо',
    'operations_edit_success': 'Операция жаңыртылды',
    'operations_rate': 'Алмашуу курсу',
    'operations_total': 'Берүүчү жалпы сумма',
    'operations_amount': 'Валюта суммасы',
    'operations_filter_sort_newest': 'Жаңылары',
    'operations_filter_sort_oldest': 'Эскилери',
    'operations_filter_sort_amount_asc': 'Сумма ↑',
    'operations_filter_sort_amount_desc': 'Сумма ↓',
    'operations_clear_filters': 'Чыпкаларды тазалоо',
    'operations_found': 'Табылды:',

    
    'cash_title': 'Касса',
    'cash_balances': 'Калдыктар',
    'cash_register_open': 'Смена ачык',
    'cash_register_closed': 'Смена ачык эмес',
    'cash_register_open_desc': 'Ишти баштоо үчүн сменаны ачыңыз',
    'cash_register_close': 'Сменаны жабуу',
    'cash_open_shift': 'Сменаны ачуу',
    'cash_transaction': 'Транзакция',
    'cash_available': 'Жеткиликтүү',
    'cash_reserved': 'Резервделген',
    'cash_cashier': 'Кассир',
    'cash_opened_at': 'Ачылган',
    'cash_opening_balance': 'Баштапкы калдыктар',
    'cash_no_data': 'Маалымат жок',

    
    'currencies_title': 'Валюталар',
    'currencies_buy': 'Сатып алуу',
    'currencies_sell': 'Сатуу',

    
    'analytics_title': 'Аналитика',
    'analytics_no_data': 'Көрсөтүү үчүн маалымат жок',
    'analytics_no_data_desc': 'Операциялардан кийин статистика пайда болот',
    'analytics_overall': 'Жалпы статистика',
    'analytics_operations_today': 'Бүгүнкү операциялар',
    'analytics_buys_sells': 'Сатып алуулар / Сатуулар',
    'analytics_turnover': 'Жүгүртүү (сом)',
    'analytics_clients': 'Кардарлар',
    'analytics_rates': 'Валюта курстары',
    'analytics_daily_chart': 'Күндөр боюнча операциялар',
    'analytics_popular_currencies': 'Популярдуу валюталар',
    'analytics_profitability': 'Рентабелдүүлүк (маржа %)',
    'analytics_cashiers': 'Кассирлер',
    'analytics_cash_balances': 'Кассадагы калдыктар',
    'analytics_reports': 'Отчёты',

    
    'reports_title': 'Отчёттор',
    'reports_subtitle': 'Отчётторду жүктөө',
    'reports_desc':
        'Маалыматтарды CSV, Excel же PDF форматында бир баскыч менен экспорттоо',
    'reports_daily': 'Күндүк отчёт',
    'reports_daily_desc': 'Күндүн жыйынтыгы: операциялар, жүгүртүү, калдыктар',
    'reports_monthly': 'Айлык отчёт',
    'reports_monthly_desc': 'Ай ичиндеги күндөр боюнча статистика',
    'reports_operations': 'Операцияларды экспорттоо',
    'reports_operations_desc': 'Бардык операциялар таблицада',
    'reports_cash': 'Кассаны экспорттоо',
    'reports_cash_desc': 'Кассадагы акча кыймылы',
    'reports_download': 'Жүктөө',
    'reports_generating': 'Отчёт түзүлүүдө...',
    'reports_saved': 'Файл сакталды',
    'reports_saved_desc':
        'Файл колдонууга даяр. Жөнөтүү же сактоо үчүн «Бөлүшүү» баскычын басыңыз.',
    'reports_open_share': 'Бөлүшүү / Сактоо',

    
    'general_retry': 'Кайталоо',
    'general_refresh': 'Жаңыртуу',
    'general_loading': 'Жүктөлүүдө...',
    'general_error': 'Ката',
    'general_success': 'Ийгиликтүү',
    'general_close': 'Жабуу',
    'general_ops': 'оп.',
    'general_today': 'Бүгүн',
    'general_yesterday': 'Кечээ',
    'general_just_now': 'Жаңы эле',
    'general_min_ago': 'мүн. мурун',
    'general_hours_ago': 'саат. мурун',
    'general_days_ago': 'күн. мурун',
    'general_som': 'сом',

    'error_retry': 'Кайталоо',
    'error_close': 'Жабуу',
    'footer_made_with_love': 'Сүйүү менен жасалды',
    'update_available': 'Жаңыртуу жеткиликтүү',
    'update_version': 'Версия {version}',
    'update_required': 'Милдеттүү жаңыртуу',
    'update_whats_new': 'Эмне жаңы:',
    'update_link': 'Жаңыртуу шилтемеси: {url}',
    'update_now': 'Азыр жаңыртуу',
    'update_later': 'Кийинчерээк',
    'lock_wrong_pin': 'Туура эмес PIN-код',
    'operation_card_cancel': 'Жокко чыгаруу',
    'operation_card_edit': 'Оңдоо',
    'operation_card_rate': 'Курс: {rate}',
    'operation_card_total': 'Жалпы: {amount}',
    'operation_detail_edit_tooltip': 'Оңдоо',
    'operation_detail_amount': 'Операция суммасы',
    'operation_detail_rate_label': 'Курс',
    'operation_detail_total_som': 'Сом менен жалпы',
    'operation_detail_client': 'Кардар',
    'operation_detail_client_name': 'Аты',
    'operation_detail_client_company': 'Компания',
    'operation_detail_details': 'Толук маалымат',
    'operation_detail_cashier': 'Кассир',
    'operation_detail_created': 'Түзүлгөн күнү',
    'operation_detail_updated': 'Акыркы өзгөртүү',
    'operation_detail_id': 'ID операция',
    'operation_detail_comment': 'Комментарий',
    'operation_detail_edit_button': 'Операцияны оңдоо',
    'operation_detail_status': 'Статус',
    'operation_detail_status_created': 'Операция түзүлдү',
    'operation_detail_status_created_sub': 'Системада өткөрүлдү',
    'operation_detail_status_executed': 'Аткарылды',
    'operation_detail_status_cancelled': 'Жокко чыгарылды',
    'operation_detail_status_partial': 'Жарым-жартылай жокко чыгарылды',
    'operation_detail_status_executed_sub': 'Операция ийгиликтүү аякталды',
    'operation_detail_status_cancelled_sub': 'Операция жокко чыгарылды',
    'operation_detail_status_partial_sub': 'Бир бөлүгү жокко чыгарылды',
    'create_operation_select_currency': 'Валюта тандаңыз',
    'create_operation_insufficient_kgs': 'Кассада сом (KGS) жетишсиз. Жеткиликтүү: {balance}, талап кылынат: {required}',
    'create_operation_insufficient_currency': 'Кассада {currency} жетишсиз. Жеткиликтүү: {balance}',
    'create_operation_success_updated': 'Операция жаңыртылды',
    'create_operation_error_update': 'Операцияны жаңыртууда ката',
    'create_operation_success_created': 'Операция ийгиликтүү түзүлдү',
    'create_operation_error_create': 'Операцияны түзүүдө ката',
    'create_operation_title_edit': 'Операцияны оңдоо',
    'create_operation_title_new': 'Жаңы операция',
    'create_operation_type': 'Операция түрү',
    'create_operation_currency': 'Валюта',
    'create_operation_currency_select': 'Валюта тандаңыз',
    'create_operation_params': 'Операция параметрлери',
    'create_operation_params_hint': 'Кандайдыр бир эки талааны өзгөртүү үчүнчүсүн автоматтык түрдө кайра эсептейт',
    'create_operation_amount_buy_label': 'Сатып алуу суммасы (валюта)',
    'create_operation_amount_sell_label': 'Сатуу суммасы (валюта)',
    'create_operation_amount_required': 'Сумманы киргизиңиз',
    'create_operation_amount_invalid': 'Туура эмес сумма',
    'create_operation_rate_label': 'Алмашуу курсу',
    'create_operation_rate_required': 'Курсту киргизиңиз',
    'create_operation_rate_invalid': 'Туура эмес курс',
    'create_operation_total_label': 'Берүүчү жалпы сумма (сом)',
    'create_operation_total_required': 'Жалпы сумманы киргизиңиз',
    'create_operation_total_invalid': 'Туура эмес сумма',
    'create_operation_summary_amount': 'Сумма',
    'create_operation_summary_rate': 'Курс',
    'create_operation_summary_total': 'Жалпы',
    'create_operation_client_info': 'Кардар жөнүндө маалымат',
    'create_operation_client_name': 'Кардардын аты (милдеттүү эмес)',
    'create_operation_client_company': 'Компания (милдеттүү эмес)',
    'create_operation_comment_label': 'Комментарий',
    'create_operation_comment_optional': 'Комментарий (милдеттүү эмес)',
    'create_operation_save': 'Өзгөртүүлөрдү сактоо',
    'create_operation_create': 'Операция түзүү',
    'operations_filter_empty': 'Чыпка параметрлерин өзгөртүүгө аракет кылыңыз',
    'operations_empty_action': 'Биринчи операцияны түзүү үчүн төмөнкү баскычты басыңыз',
    'operations_cancel_title': 'Операцияны жокко чыгаруу',
    'operations_cancel_confirm': '№{number} операцияны жокко чыгаруу?',
    'operations_cancel_button': 'Жокко чыгаруу',
    'operations_cancel_confirm_button': 'Жокко чыгарууну тастыктоо',
    'operations_cancel_success': 'Операция жокко чыгарылды',
    'operations_cancel_error': 'Операцияны жокко чыгарууда ката',
    'operations_no_results': 'Операциялар жок',
    'operations_filter_currency_title': 'Валюта боюнча чыпка',
    'cash_no_balances': 'Баланстар жок',
    'cash_no_balances_desc': 'Сменаны ачкандан жана биринчи операцияларды жасагандан кийин баланстар пайда болот',
    'close_register_success': 'Смена ийгиликтүү жабылды',
    'close_register_error': 'Сменаны жабууда ката',
    'close_register_title': 'Сменаны жабуу',
    'close_register_loading': 'Күндүн жыйынтыгы жүктөлүүдө...',
    'close_register_summary': 'Күндүн жыйынтыгы',
    'close_register_total_ops': 'Бардык операциялар',
    'close_register_buys': 'Сатып алуулар',
    'close_register_sells': 'Сатуулар',
    'close_register_turnover': 'Жүгүртүү: {amount}',
    'close_register_cancelled': 'Жокко чыгарылган: {count}',
    'close_register_enter_balances': 'Валюталар боюнча фактылык калдыктарды киргизиңиз',
    'close_register_required': 'Милдеттүү талаа',
    'close_register_invalid': 'Туура эмес сумма',
    'close_register_comment': 'Комментарий (милдеттүү эмес)',
    'close_register_cancel': 'Жокко чыгаруу',
    'close_register_confirm': 'Сменаны жабуу',
    'open_register_need_balance': 'Жок дегенде бир калдык киргизиңиз',
    'open_register_success': 'Смена ийгиликтүү ачылды',
    'open_register_error': 'Сменаны ачууда ката',
    'open_register_title': 'Сменаны ачуу',
    'open_register_hint': 'Валюталар боюнча баштапкы калдыктарды киргизиңиз',
    'open_register_invalid': 'Туура эмес сумма',
    'open_register_comment': 'Комментарий (милдеттүү эмес)',
    'open_register_cancel': 'Жокко чыгаруу',
    'open_register_confirm': 'Сменаны ачуу',
    'transaction_select_currency': 'Валюта тандаңыз',
    'transaction_success': 'Транзакция ийгиликтүү түзүлдү',
    'transaction_error': 'Транзакцияны түзүүдө ката',
    'transaction_title': 'Транзакция',
    'transaction_deposit': 'Киргизүү',
    'transaction_withdrawal': 'Чыгаруу',
    'transaction_currency': 'Валюта',
    'transaction_currency_placeholder': 'Валюта тандаңыз',
    'transaction_amount': 'Сумма',
    'transaction_amount_required': 'Сумманы киргизиңиз',
    'transaction_amount_invalid': 'Туура эмес сумма',
    'transaction_client_name': 'Кардар (милдеттүү эмес)',
    'transaction_client_company': 'Компания (милдеттүү эмес)',
    'transaction_rate': 'Курс (эгер чет элдик валюта болсо)',
    'transaction_rate_hint': 'Милдеттүү эмес',
    'transaction_comment': 'Комментарий (милдеттүү эмес)',
    'transaction_cancel': 'Жокко чыгаруу',
    'transaction_create': 'Түзүү',
    'currencies_empty': 'Валюта курстары маалымат жүктөлгөндөн кийин пайда болот',
    'currencies_total': 'Бардыгы',
    'currencies_active': 'Активдүү',
    'currencies_with_rates': 'Курстар менен',
    'currencies_edit_rates': 'Курстарды оңдоо',
    'currencies_active_status': 'Активдүү',
    'currencies_inactive_status': 'Активдүү эмес',
    'currencies_no_rates': 'Курстар орнотулган эмес',
    'currencies_no_rates_short': 'Курстар көрсөтүлгөн эмес',
    'currencies_rate_required': 'Курсту киргизиңиз',
    'currencies_rate_invalid': 'Туура эмес сан',
    'analytics_operations': 'Операциялар',
    'analytics_turnover_short': 'Жүгүртүү',
    'analytics_buys_sells_short': 'Сатып алуулар/Сатуулар',
    'analytics_clients_short': 'Кардарлар',
    'analytics_operations_today_short': 'Бүгүнкү операциялар',
    'analytics_turnover_today': 'Бүгүнкү жүгүртүү',
    'analytics_buys_sells_today': 'Сатып алуулар / Сатуулар',
    'analytics_clients_today': 'Кардарлар',
    'analytics_period_7d': '7 күн',
    'analytics_period_14d': '14 күн',
    'analytics_period_30d': '30 күн',
    'analytics_ops_count': '{count} оп.',
    'analytics_available': 'Жеткиликтүү: {balance}',
    'charts_no_data_period': 'Мөөнөт үчүн маалымат жок',
    'charts_tooltip_buy_sell': 'Сатып алуу: {buy} • Сатуу: {sell}',
    'charts_no_data': 'Маалымат жок',
    'charts_ops_turnover': 'Операциялар: {ops}\nЖүгүртүү: {turnover}',
    'charts_no_profitability': 'Рентабелдүүлүк жөнүндө маалымат жок',
    'charts_profit': 'Киреше: {spread}\nМаржа: {margin}%',
    'reports_cashier_shift': 'Кассир сменасы боюнча отчёт',
    'reports_cashier_shift_desc': 'PDF-отчёт: калдыктар, операциялар, смена жыйынтыгы',
    'settings_pin_6_digits': 'PIN-код 6 цифра болушу керек',
    'settings_pin_mismatch': 'PIN-коддор дал келбейт',
    'settings_pin_set': 'PIN-код орнотулду',
    'settings_pin_removed': 'PIN-код өчүрүлдү',
    'settings_pin_new': 'Жаңы PIN-код',
    'settings_pin_confirm': 'PIN-кодду тастыктоо',
    'settings_pin_delete': 'PIN өчүрүү',
    'settings_pin_save': 'Сактоо',
    'settings_support_message': 'Салам! Мага My Exchange колдонмосу менен жардам керек.',
    'entity_operation_type_buy': 'Сатып алуу',
    'entity_operation_type_sell': 'Сатуу',
    'entity_operation_status_active': 'Активдүү',
    'entity_operation_status_cancelled': 'Жокко чыгарылды',
    'entity_operation_status_partial': 'Жарым-жартылай жокко чыгарылды',
    'entity_user_role_cashier': 'Кассир',
    'entity_user_role_senior_cashier': 'Улук кассир',
    'entity_user_role_admin': 'Администратор',
    'entity_transaction_type_deposit': 'Накталай акча киргизүү',
    'entity_transaction_type_withdrawal': 'Накталай акча чыгаруу',
    'entity_transaction_type_inkassation': 'Инкассация',

    
    'onboarding_skip': 'Өткөрүү',
    'onboarding_next': 'Кийинки',
    'onboarding_get_started': 'Баштоо',
    'onboarding_welcome_title': 'My Exchange колдонмосуна кош келиңиз',
    'onboarding_welcome_desc': 'Акча алмашуу операцияларын тез жана натыйжалуу башкарыңыз. Валюта курсун көзөмөлдөп, кассаны жүргүзүп, кирешени талдаңыз.',
    'onboarding_operations_title': 'Операциялар жана касса',
    'onboarding_operations_desc': 'Валюта сатып алуу жана сатуу операцияларын түзүңүз, касса сменаларын башкарыңыз, акча кыймылын көзөмөлдөңүз.',
    'onboarding_analytics_title': 'Аналитика жана отчеттор',
    'onboarding_analytics_desc': 'Кирешени, популярдуу валюталарды көзөмөлдөп, толук отчетторду бир баскыч менен жүктөп алыңыз.',
  };

  
  static const Map<String, String> _en = {
    
    'app_name': 'My Exchange',
    'app_title': 'My Exchange',

    
    'nav_operations': 'Operations',
    'nav_cash': 'Cash',
    'nav_currencies': 'Currencies',
    'nav_analytics': 'Analytics',
    'nav_settings': 'Profile',

    
    'login_title': 'Sign In',
    'login_username': 'Username',
    'login_password': 'Password',
    'login_button': 'Sign In',
    'login_error': 'Login failed',
    'login_username_required': 'Enter username',
    'login_password_required': 'Enter password',
    'login_password_min': 'Password must be at least 6 characters',
    'login_version': 'Version',
    'login_biometric': 'Sign in with Touch ID / Face ID',
    'login_biometric_error': 'Biometric authentication is not available',
    'login_biometric_failed': 'Biometric login failed',
    'login_biometric_save': 'Remember for quick login',
    'login_biometric_reason': 'Authenticate to sign in to the app',

    
    'settings_title': 'Profile & Settings',
    'settings_profile': 'Profile',
    'settings_user_info': 'User Information',
    'settings_role': 'Role',
    'settings_email': 'Email',
    'settings_phone': 'Phone',
    'settings_language': 'Language',
    'settings_language_ru': 'Русский',
    'settings_language_kg': 'Кыргызча',
    'settings_language_en': 'English',
    'settings_language_uz': "O'zbekcha",
    'settings_language_uzCyrillic': 'Ўзбекча',
    'settings_app_version': 'App Version',
    'settings_logout': 'Log Out',
    'settings_logout_confirm': 'Are you sure you want to log out?',
    'settings_logout_confirm_desc':
        'You will need to enter your username and password to log back in.',
    'settings_cancel': 'Cancel',
    'settings_confirm': 'Yes, log out',
    'settings_privacy_policy': 'Privacy Policy',
    'settings_contact_support': 'Contact Support',
    'settings_delete_account': 'Request Account Deletion',
    'settings_delete_account_desc':
        'Send a request to delete your account and all related data.',
    'settings_delete_account_confirm':
        'Request sent. We will contact you shortly.',
    'settings_theme': 'Theme',
    'settings_theme_light': 'Light',
    'settings_theme_dark': 'Dark',
    'settings_pin_code': 'PIN Code',
    'settings_pin_code_desc': 'Set a PIN code to unlock the app',
    'settings_biometric_login': 'Biometric Login',
    'settings_biometric_login_desc': 'Use Touch ID / Face ID for quick login',
    'lock_title': 'Enter PIN Code',
    'lock_subtitle': 'Enter your PIN to unlock the app',
    'lock_biometric': 'Touch ID / Face ID',
    'lock_biometric_reason': 'Authenticate to unlock the app',
    'lock_biometric_failed': 'Biometric failed. Enter PIN code',
    'lock_or': 'or',
    'settings_support_email': 'salievyt@gmail.com',
    'settings_support_chat': 'WhatsApp, Telegram',
    'settings_support_title': 'Contact Support',
    'settings_support_description': 'Choose your preferred contact method',
    'settings_privacy_note':
        'By pressing "Log Out" you end your current session.',

    
    'operations_title': 'Operations',
    'operations_create': 'Operation',
    'operations_empty': 'No operations',
    'operations_load': 'Load',
    'operations_today': 'Today',
    'operations_buys': 'Buys',
    'operations_sells': 'Sells',
    'operations_buy': 'Buy',
    'operations_sell': 'Sell',
    'operations_search': 'Search by number, client...',
    'operations_search_hint': 'Operation number, client name',
    'operations_filter_type': 'Type',
    'operations_filter_all': 'All',
    'operations_filter_period': 'Period',
    'operations_filter_period_today': 'Today',
    'operations_filter_period_week': 'Week',
    'operations_filter_period_month': 'Month',
    'operations_filter_period_all': 'All time',
    'operations_filter_sort': 'Sort',
    'operations_filter_period_custom': 'Custom period',
    'operations_filter_currency': 'Currency',
    'operations_filter_currency_all': 'All currencies',
    'operations_columns': 'View',
    'operations_columns_1': '1 column',
    'operations_columns_2': '2 columns',
    'operations_filter_date_from': 'From',
    'operations_filter_date_to': 'To',
    'operations_filter_date_apply': 'Apply',
    'operations_edit': 'Edit',
    'operations_save': 'Save',
    'operations_edit_title': 'Edit Operation',
    'operations_edit_success': 'Operation updated',
    'operations_rate': 'Exchange Rate',
    'operations_total': 'Total to Pay',
    'operations_amount': 'Currency Amount',
    'operations_filter_sort_newest': 'Newest',
    'operations_filter_sort_oldest': 'Oldest',
    'operations_filter_sort_amount_asc': 'Amount ↑',
    'operations_filter_sort_amount_desc': 'Amount ↓',
    'operations_clear_filters': 'Clear filters',
    'operations_found': 'Found:',

    
    'cash_title': 'Cash Register',
    'cash_balances': 'Balances',
    'cash_register_open': 'Shift Open',
    'cash_register_closed': 'Shift Closed',
    'cash_register_open_desc': 'Open the shift to start working',
    'cash_register_close': 'Close Shift',
    'cash_open_shift': 'Open Shift',
    'cash_transaction': 'Transaction',
    'cash_available': 'Available',
    'cash_reserved': 'Reserved',
    'cash_cashier': 'Cashier',
    'cash_opened_at': 'Opened at',
    'cash_opening_balance': 'Opening Balances',
    'cash_no_data': 'No data',

    
    'currencies_title': 'Currencies',
    'currencies_buy': 'Buy',
    'currencies_sell': 'Sell',

    
    'analytics_title': 'Analytics',
    'analytics_no_data': 'No data to display',
    'analytics_no_data_desc':
        'Statistics will appear after performing operations',
    'analytics_overall': 'Overall Statistics',
    'analytics_operations_today': 'Operations today',
    'analytics_buys_sells': 'Buys / Sells',
    'analytics_turnover': 'Turnover (som)',
    'analytics_clients': 'Clients',
    'analytics_rates': 'Exchange Rates',
    'analytics_daily_chart': 'Operations by day',
    'analytics_popular_currencies': 'Popular Currencies',
    'analytics_profitability': 'Profitability (margin %)',
    'analytics_cashiers': 'Cashiers',
    'analytics_cash_balances': 'Cash Balances',
    'analytics_reports': 'Reports',

    
    'reports_title': 'Reports',
    'reports_subtitle': 'Download Reports',
    'reports_desc': 'Export data in CSV, Excel or PDF format with one click',
    'reports_daily': 'Daily Report',
    'reports_daily_desc': 'Daily summary: operations, turnover, balances',
    'reports_monthly': 'Monthly Report',
    'reports_monthly_desc': 'Monthly statistics by day',
    'reports_operations': 'Export Operations',
    'reports_operations_desc': 'All operations for the period in a table',
    'reports_cash': 'Export Cash',
    'reports_cash_desc': 'Cash flow movement',
    'reports_download': 'Download',
    'reports_generating': 'Generating report...',
    'reports_saved': 'File saved',
    'reports_saved_desc':
        'File is ready to use. Press "Share" to send or save it.',
    'reports_open_share': 'Share / Save',

    
    'general_retry': 'Retry',
    'general_refresh': 'Refresh',
    'general_loading': 'Loading...',
    'general_error': 'Error',
    'general_success': 'Success',
    'general_close': 'Close',
    'general_ops': 'ops.',
    'general_today': 'Today',
    'general_yesterday': 'Yesterday',
    'general_just_now': 'Just now',
    'general_min_ago': 'min. ago',
    'general_hours_ago': 'h. ago',
    'general_days_ago': 'd. ago',
    'general_som': 'som',

    'error_retry': 'Retry',
    'error_close': 'Close',
    'footer_made_with_love': 'Made with love',
    'update_available': 'Update Available',
    'update_version': 'Version {version}',
    'update_required': 'Required Update',
    'update_whats_new': "What's New:",
    'update_link': 'Update link: {url}',
    'update_now': 'Update Now',
    'update_later': 'Later',
    'lock_wrong_pin': 'Wrong PIN code',
    'operation_card_cancel': 'Cancel',
    'operation_card_edit': 'Edit',
    'operation_card_rate': 'Rate: {rate}',
    'operation_card_total': 'Total: {amount}',
    'operation_detail_edit_tooltip': 'Edit',
    'operation_detail_amount': 'Operation Amount',
    'operation_detail_rate_label': 'Rate',
    'operation_detail_total_som': 'Total in soms',
    'operation_detail_client': 'Client',
    'operation_detail_client_name': 'Name',
    'operation_detail_client_company': 'Company',
    'operation_detail_details': 'Details',
    'operation_detail_cashier': 'Cashier',
    'operation_detail_created': 'Created Date',
    'operation_detail_updated': 'Last Modified',
    'operation_detail_id': 'Operation ID',
    'operation_detail_comment': 'Comment',
    'operation_detail_edit_button': 'Edit Operation',
    'operation_detail_status': 'Status',
    'operation_detail_status_created': 'Operation Created',
    'operation_detail_status_created_sub': 'Processed in system',
    'operation_detail_status_executed': 'Executed',
    'operation_detail_status_cancelled': 'Cancelled',
    'operation_detail_status_partial': 'Partially Cancelled',
    'operation_detail_status_executed_sub': 'Operation completed successfully',
    'operation_detail_status_cancelled_sub': 'Operation cancelled',
    'operation_detail_status_partial_sub': 'Part of operation cancelled',
    'create_operation_select_currency': 'Select currency',
    'create_operation_insufficient_kgs': 'Insufficient som (KGS) in cash register. Available: {balance}, required: {required}',
    'create_operation_insufficient_currency': 'Insufficient {currency} in cash register. Available: {balance}',
    'create_operation_success_updated': 'Operation updated',
    'create_operation_error_update': 'Error updating operation',
    'create_operation_success_created': 'Operation created successfully',
    'create_operation_error_create': 'Error creating operation',
    'create_operation_title_edit': 'Edit Operation',
    'create_operation_title_new': 'New Operation',
    'create_operation_type': 'Operation Type',
    'create_operation_currency': 'Currency',
    'create_operation_currency_select': 'Select currency',
    'create_operation_params': 'Operation Parameters',
    'create_operation_params_hint': 'Changing any two fields automatically recalculates the third',
    'create_operation_amount_buy_label': 'Purchase Amount (currency)',
    'create_operation_amount_sell_label': 'Sale Amount (currency)',
    'create_operation_amount_required': 'Enter amount',
    'create_operation_amount_invalid': 'Invalid amount',
    'create_operation_rate_label': 'Exchange Rate',
    'create_operation_rate_required': 'Enter rate',
    'create_operation_rate_invalid': 'Invalid rate',
    'create_operation_total_label': 'Total to Pay (som)',
    'create_operation_total_required': 'Enter total amount',
    'create_operation_total_invalid': 'Invalid amount',
    'create_operation_summary_amount': 'Amount',
    'create_operation_summary_rate': 'Rate',
    'create_operation_summary_total': 'Total',
    'create_operation_client_info': 'Client Information',
    'create_operation_client_name': 'Client Name (optional)',
    'create_operation_client_company': 'Company (optional)',
    'create_operation_comment_label': 'Comment',
    'create_operation_comment_optional': 'Comment (optional)',
    'create_operation_save': 'Save Changes',
    'create_operation_create': 'Create Operation',
    'operations_filter_empty': 'Try changing the filter parameters',
    'operations_empty_action': 'Click the button below to create your first operation',
    'operations_cancel_title': 'Cancel Operation',
    'operations_cancel_confirm': 'Cancel operation #{number}?',
    'operations_cancel_button': 'Cancel',
    'operations_cancel_confirm_button': 'Confirm Cancellation',
    'operations_cancel_success': 'Operation cancelled',
    'operations_cancel_error': 'Error cancelling operation',
    'operations_no_results': 'No operations',
    'operations_filter_currency_title': 'Filter by currency',
    'cash_no_balances': 'No balances',
    'cash_no_balances_desc': 'Balances will appear after opening a shift and making the first operations',
    'close_register_success': 'Shift closed successfully',
    'close_register_error': 'Error closing shift',
    'close_register_title': 'Close Shift',
    'close_register_loading': 'Loading day summary...',
    'close_register_summary': 'Day Summary',
    'close_register_total_ops': 'Total Operations',
    'close_register_buys': 'Purchases',
    'close_register_sells': 'Sales',
    'close_register_turnover': 'Turnover: {amount}',
    'close_register_cancelled': 'Cancelled: {count}',
    'close_register_enter_balances': 'Enter actual balances by currency',
    'close_register_required': 'Required field',
    'close_register_invalid': 'Invalid amount',
    'close_register_comment': 'Comment (optional)',
    'close_register_cancel': 'Cancel',
    'close_register_confirm': 'Close Shift',
    'open_register_need_balance': 'Enter at least one balance',
    'open_register_success': 'Shift opened successfully',
    'open_register_error': 'Error opening shift',
    'open_register_title': 'Open Shift',
    'open_register_hint': 'Enter initial balances by currency',
    'open_register_invalid': 'Invalid amount',
    'open_register_comment': 'Comment (optional)',
    'open_register_cancel': 'Cancel',
    'open_register_confirm': 'Open Shift',
    'transaction_select_currency': 'Select currency',
    'transaction_success': 'Transaction created successfully',
    'transaction_error': 'Error creating transaction',
    'transaction_title': 'Transaction',
    'transaction_deposit': 'Deposit',
    'transaction_withdrawal': 'Withdrawal',
    'transaction_currency': 'Currency',
    'transaction_currency_placeholder': 'Select currency',
    'transaction_amount': 'Amount',
    'transaction_amount_required': 'Enter amount',
    'transaction_amount_invalid': 'Invalid amount',
    'transaction_client_name': 'Client (optional)',
    'transaction_client_company': 'Company (optional)',
    'transaction_rate': 'Rate (if foreign currency)',
    'transaction_rate_hint': 'Optional',
    'transaction_comment': 'Comment (optional)',
    'transaction_cancel': 'Cancel',
    'transaction_create': 'Create',
    'currencies_empty': 'Exchange rates will appear after data loading',
    'currencies_total': 'Total',
    'currencies_active': 'Active',
    'currencies_with_rates': 'With rates',
    'currencies_edit_rates': 'Edit Rates',
    'currencies_active_status': 'Active',
    'currencies_inactive_status': 'Inactive',
    'currencies_no_rates': 'Rates not set',
    'currencies_no_rates_short': 'Rates not specified',
    'currencies_rate_required': 'Enter rate',
    'currencies_rate_invalid': 'Invalid number',
    'analytics_operations': 'Operations',
    'analytics_turnover_short': 'Turnover',
    'analytics_buys_sells_short': 'Buys/Sells',
    'analytics_clients_short': 'Clients',
    'analytics_operations_today_short': 'Operations today',
    'analytics_turnover_today': 'Turnover today',
    'analytics_buys_sells_today': 'Buys / Sells',
    'analytics_clients_today': 'Clients',
    'analytics_period_7d': '7 days',
    'analytics_period_14d': '14 days',
    'analytics_period_30d': '30 days',
    'analytics_ops_count': '{count} ops.',
    'analytics_available': 'Available: {balance}',
    'charts_no_data_period': 'No data for the period',
    'charts_tooltip_buy_sell': 'Buy: {buy} • Sell: {sell}',
    'charts_no_data': 'No data',
    'charts_ops_turnover': 'Operations: {ops}\nTurnover: {turnover}',
    'charts_no_profitability': 'No profitability data',
    'charts_profit': 'Profit: {spread}\nMargin: {margin}%',
    'reports_cashier_shift': 'Cashier Shift Report',
    'reports_cashier_shift_desc': 'PDF report: balances, operations, shift summary',
    'settings_pin_6_digits': 'PIN code must be 6 digits',
    'settings_pin_mismatch': 'PIN codes do not match',
    'settings_pin_set': 'PIN code set',
    'settings_pin_removed': 'PIN code removed',
    'settings_pin_new': 'New PIN code',
    'settings_pin_confirm': 'Confirm PIN code',
    'settings_pin_delete': 'Delete PIN',
    'settings_pin_save': 'Save',
    'settings_support_message': 'Hello! I need help with the My Exchange app.',
    'entity_operation_type_buy': 'Buy',
    'entity_operation_type_sell': 'Sell',
    'entity_operation_status_active': 'Active',
    'entity_operation_status_cancelled': 'Cancelled',
    'entity_operation_status_partial': 'Partially Cancelled',
    'entity_user_role_cashier': 'Cashier',
    'entity_user_role_senior_cashier': 'Senior Cashier',
    'entity_user_role_admin': 'Administrator',
    'entity_transaction_type_deposit': 'Cash Deposit',
    'entity_transaction_type_withdrawal': 'Cash Withdrawal',
    'entity_transaction_type_inkassation': 'Inkassation',

    
    'onboarding_skip': 'Skip',
    'onboarding_next': 'Next',
    'onboarding_get_started': 'Get Started',
    'onboarding_welcome_title': 'Welcome to My Exchange',
    'onboarding_welcome_desc': 'Manage currency exchange operations quickly and efficiently. Track exchange rates, manage cash register, and analyze profits.',
    'onboarding_operations_title': 'Operations & Cash',
    'onboarding_operations_desc': 'Create buy and sell currency operations, manage cash register shifts, and track money flow in real time.',
    'onboarding_analytics_title': 'Analytics & Reports',
    'onboarding_analytics_desc': 'Track profitability, popular currencies, and download detailed reports with one click.',
  };

  
  static const Map<String, String> _uz = {
    
    'app_name': 'My Exchange',
    'app_title': "Mening Ayirboshlash",

    
    'nav_operations': 'Operatsiyalar',
    'nav_cash': 'Kassa',
    'nav_currencies': 'Valyutalar',
    'nav_analytics': 'Analitika',
    'nav_settings': 'Profil',

    
    'login_title': 'Tizimga kirish',
    'login_username': 'Foydalanuvchi nomi',
    'login_password': 'Parol',
    'login_button': 'Kirish',
    'login_error': 'Kirish xatosi',
    'login_username_required': 'Foydalanuvchi nomini kiriting',
    'login_password_required': 'Parolni kiriting',
    'login_password_min': "Parol kamida 6 ta belgidan iborat bo'lishi kerak",
    'login_version': 'Versiya',
    'login_biometric': 'Touch ID / Face ID orqali kirish',
    'login_biometric_error': 'Biometrik autentifikatsiya mavjud emas',
    'login_biometric_failed': 'Biometriya orqali kirish muvaffaqiyatsiz',
    'login_biometric_save': 'Tez kirish uchun eslab qolish',
    'login_biometric_reason': 'Ilovaga kirish uchun shaxsingizni tasdiqlang',

    
    'settings_title': "Profil va sozlamalar",
    'settings_profile': 'Profil',
    'settings_user_info': "Foydalanuvchi ma'lumotlari",
    'settings_role': 'Lavozim',
    'settings_email': 'Email',
    'settings_phone': 'Telefon',
    'settings_language': 'Til',
    'settings_language_ru': 'Русский',
    'settings_language_kg': 'Кыргызча',
    'settings_language_en': 'English',
    'settings_language_uz': "O'zbekcha",
    'settings_language_uzCyrillic': 'Ўзбекча',
    'settings_app_version': 'Ilova versiyasi',
    'settings_logout': 'Chiqish',
    'settings_logout_confirm': 'Chiqishni xohlaysizmi?',
    'settings_logout_confirm_desc':
        "Qayta kirish uchun login va parol kerak bo'ladi.",
    'settings_cancel': 'Bekor qilish',
    'settings_confirm': 'Ha, chiqish',
    'settings_privacy_policy': 'Maxfiylik siyosati',
    'settings_contact_support': "Qo'llab-quvvatlash",
    'settings_delete_account': "Akkauntni o'chirish",
    'settings_delete_account_desc':
        "Akkauntingizni va barcha ma'lumotlarni o'chirish so'rovini yuborish.",
    'settings_delete_account_confirm':
        "So'rov yuborildi. Tez orada siz bilan bog'lanamiz.",
    'settings_theme': 'Mavzu',
    'settings_theme_light': "Yorug'",
    'settings_theme_dark': "Qorong'i",
    'settings_pin_code': 'PIN-kod',
    'settings_pin_code_desc': 'Ilovaga kirish uchun PIN-kod o\'rnatish',
    'settings_biometric_login': 'Biometrik kirish',
    'settings_biometric_login_desc':
        'Tez kirish uchun Touch ID / Face ID dan foydalanish',
    'lock_title': 'PIN-kodni kiriting',
    'lock_subtitle': 'Ilovani ochish uchun PIN-kodni kiriting',
    'lock_biometric': 'Touch ID / Face ID',
    'lock_biometric_reason': 'Ilovaga kirish uchun shaxsingizni tasdiqlang',
    'lock_biometric_failed': 'Biometriya xatosi. PIN-kodni kiriting',
    'lock_or': 'yoki',
    'settings_support_email': 'salievyt@gmail.com',
    'settings_support_chat': 'WhatsApp, Telegram',
    'settings_support_title': "Qo'llab-quvvatlash bilan bog'lanish",
    'settings_support_description': "Qulay aloqa usulini tanlang",
    'settings_privacy_note':
        '"Chiqish" tugmasini bosish orqali siz joriy seansni yakunlaysiz.',

    
    'operations_title': 'Operatsiyalar',
    'operations_create': 'Operatsiya',
    'operations_empty': "Operatsiyalar yo'q",
    'operations_load': 'Yuklash',
    'operations_today': 'Bugun',
    'operations_buys': 'Xaridlar',
    'operations_sells': 'Sotuvlar',
    'operations_buy': 'Xarid',
    'operations_sell': 'Sotuv',
    'operations_search': "Raqam, mijoz nomi bo'yicha qidirish...",
    'operations_search_hint': 'Operatsiya raqami, mijoz nomi',
    'operations_filter_type': 'Turi',
    'operations_filter_all': 'Barchasi',
    'operations_filter_period': 'Davr',
    'operations_filter_period_today': 'Bugun',
    'operations_filter_period_week': 'Hafta',
    'operations_filter_period_month': 'Oy',
    'operations_filter_period_all': 'Barcha vaqt',
    'operations_filter_sort': 'Saralash',
    'operations_filter_period_custom': "O'z davri",
    'operations_filter_currency': 'Valyuta',
    'operations_filter_currency_all': 'Barcha valyutalar',
    'operations_columns': 'Ustunlar',
    'operations_columns_1': '1 ustun',
    'operations_columns_2': '2 ustun',
    'operations_filter_date_from': 'Dan',
    'operations_filter_date_to': 'Gacha',
    'operations_filter_date_apply': "Qo'llash",
    'operations_edit': 'Tahrirlash',
    'operations_save': 'Saqlash',
    'operations_edit_title': 'Operatsiyani tahrirlash',
    'operations_edit_success': 'Operatsiya yangilandi',
    'operations_rate': 'Ayirboshlash kursi',
    'operations_total': 'Beriladigan umumiy summa',
    'operations_amount': 'Valyuta summasi',
    'operations_filter_sort_newest': 'Yangi',
    'operations_filter_sort_oldest': 'Eski',
    'operations_filter_sort_amount_asc': 'Summa ↑',
    'operations_filter_sort_amount_desc': 'Summa ↓',
    'operations_clear_filters': 'Filtrlarni tozalash',
    'operations_found': 'Topildi:',

    
    'cash_title': 'Kassa',
    'cash_balances': 'Qoldiqlar',
    'cash_register_open': 'Smena ochiq',
    'cash_register_closed': 'Smena ochiq emas',
    'cash_register_open_desc': 'Ishni boshlash uchun smenani oching',
    'cash_register_close': 'Smenani yopish',
    'cash_open_shift': 'Smenani ochish',
    'cash_transaction': 'Tranzaksiya',
    'cash_available': 'Mavjud',
    'cash_reserved': 'Zahiralangan',
    'cash_cashier': 'Kassir',
    'cash_opened_at': 'Ochilgan',
    'cash_opening_balance': 'Boshlang\'ich qoldiqlar',
    'cash_no_data': "Ma'lumot yo'q",

    
    'currencies_title': 'Valyutalar',
    'currencies_buy': 'Xarid',
    'currencies_sell': 'Sotuv',

    
    'analytics_title': 'Analitika',
    'analytics_no_data': "Ko'rsatish uchun ma'lumot yo'q",
    'analytics_no_data_desc': "Operatsiyalardan so'ng statistika paydo bo'ladi",
    'analytics_overall': 'Umumiy statistika',
    'analytics_operations_today': 'Bugungi operatsiyalar',
    'analytics_buys_sells': 'Xaridlar / Sotuvlar',
    'analytics_turnover': "Aylanma (so'm)",
    'analytics_clients': 'Mijozlar',
    'analytics_rates': 'Valyuta kurslari',
    'analytics_daily_chart': "Kunlar bo'yicha operatsiyalar",
    'analytics_popular_currencies': 'Ommabop valyutalar',
    'analytics_profitability': 'Daromadlilik (marja %)',
    'analytics_cashiers': 'Kassirlar',
    'analytics_cash_balances': 'Kassadagi qoldiqlar',
    'analytics_reports': 'Hisobotlar',

    
    'reports_title': 'Hisobotlar',
    'reports_subtitle': 'Hisobotlarni yuklab olish',
    'reports_desc':
        "Ma'lumotlarni CSV, Excel yoki PDF formatida bir tugma bilan eksport qilish",
    'reports_daily': 'Kunlik hisobot',
    'reports_daily_desc': 'Kun yakuni: operatsiyalar, aylanma, qoldiqlar',
    'reports_monthly': 'Oylik hisobot',
    'reports_monthly_desc': "Oy ichidagi kunlar bo'yicha statistika",
    'reports_operations': 'Operatsiyalarni eksport qilish',
    'reports_operations_desc': 'Barcha operatsiyalar jadvalda',
    'reports_cash': 'Kassani eksport qilish',
    'reports_cash_desc': 'Kassadagi pul harakati',
    'reports_download': 'Yuklab olish',
    'reports_generating': 'Hisobot tayyorlanmoqda...',
    'reports_saved': 'Fayl saqlandi',
    'reports_saved_desc':
        'Fayl foydalanishga tayyor. Yuborish yoki saqlash uchun "Ulashish" tugmasini bosing.',
    'reports_open_share': 'Ulashish / Saqlash',

    
    'general_retry': 'Qayta urinish',
    'general_refresh': 'Yangilash',
    'general_loading': 'Yuklanmoqda...',
    'general_error': 'Xato',
    'general_success': 'Muvaffaqiyatli',
    'general_close': 'Yopish',
    'general_ops': 'op.',
    'general_today': 'Bugun',
    'general_yesterday': 'Kecha',
    'general_just_now': 'Hozirgina',
    'general_min_ago': 'daq. oldin',
    'general_hours_ago': 'soat. oldin',
    'general_days_ago': 'kun. oldin',
    'general_som': "so'm",

    'error_retry': 'Qayta urinish',
    'error_close': 'Yopish',
    'footer_made_with_love': "Sevgi bilan qilingan",
    'update_available': 'Yangilanish mavjud',
    'update_version': 'Versiya {version}',
    'update_required': 'Majburiy yangilanish',
    'update_whats_new': "Nima yangi:",
    'update_link': "Yangilanish havolasi: {url}",
    'update_now': 'Hozir yangilash',
    'update_later': 'Keyinroq',
    'lock_wrong_pin': "Noto'g'ri PIN-kod",
    'operation_card_cancel': 'Bekor qilish',
    'operation_card_edit': 'Tahrirlash',
    'operation_card_rate': 'Kurs: {rate}',
    'operation_card_total': 'Jami: {amount}',
    'operation_detail_edit_tooltip': 'Tahrirlash',
    'operation_detail_amount': 'Operatsiya summasi',
    'operation_detail_rate_label': 'Kurs',
    'operation_detail_total_som': "So'mda jami",
    'operation_detail_client': 'Mijoz',
    'operation_detail_client_name': 'Ismi',
    'operation_detail_client_company': 'Kompaniya',
    'operation_detail_details': "Batafsil ma'lumot",
    'operation_detail_cashier': 'Kassir',
    'operation_detail_created': 'Yaratilgan sana',
    'operation_detail_updated': "So'nggi o'zgartirish",
    'operation_detail_id': 'Operatsiya ID',
    'operation_detail_comment': 'Izoh',
    'operation_detail_edit_button': 'Operatsiyani tahrirlash',
    'operation_detail_status': 'Holati',
    'operation_detail_status_created': 'Operatsiya yaratildi',
    'operation_detail_status_created_sub': 'Tizimda o\'tkazildi',
    'operation_detail_status_executed': 'Bajarildi',
    'operation_detail_status_cancelled': 'Bekor qilindi',
    'operation_detail_status_partial': 'Qisman bekor qilindi',
    'operation_detail_status_executed_sub': 'Operatsiya muvaffaqiyatli yakunlandi',
    'operation_detail_status_cancelled_sub': 'Operatsiya bekor qilindi',
    'operation_detail_status_partial_sub': 'Bir qismi bekor qilindi',
    'create_operation_select_currency': 'Valyutani tanlang',
    'create_operation_insufficient_kgs': "Kassada so'm (KGS) yetarli emas. Mavjud: {balance}, talab qilinadi: {required}",
    'create_operation_insufficient_currency': 'Kassada {currency} yetarli emas. Mavjud: {balance}',
    'create_operation_success_updated': 'Operatsiya yangilandi',
    'create_operation_error_update': 'Operatsiyani yangilashda xato',
    'create_operation_success_created': 'Operatsiya muvaffaqiyatli yaratildi',
    'create_operation_error_create': 'Operatsiyani yaratishda xato',
    'create_operation_title_edit': 'Operatsiyani tahrirlash',
    'create_operation_title_new': 'Yangi operatsiya',
    'create_operation_type': 'Operatsiya turi',
    'create_operation_currency': 'Valyuta',
    'create_operation_currency_select': 'Valyutani tanlang',
    'create_operation_params': 'Operatsiya parametrlari',
    'create_operation_params_hint': 'Har qanday ikkita maydonni o\'zgartirish uchinchisini avtomatik qayta hisoblaydi',
    'create_operation_amount_buy_label': "Sotib olish summasi (valyuta)",
    'create_operation_amount_sell_label': 'Sotish summasi (valyuta)',
    'create_operation_amount_required': 'Summani kiriting',
    'create_operation_amount_invalid': "Noto'g'ri summa",
    'create_operation_rate_label': 'Ayirboshlash kursi',
    'create_operation_rate_required': 'Kursni kiriting',
    'create_operation_rate_invalid': "Noto'g'ri kurs",
    'create_operation_total_label': "Beriladigan umumiy summa (so'm)",
    'create_operation_total_required': 'Umumiy summani kiriting',
    'create_operation_total_invalid': "Noto'g'ri summa",
    'create_operation_summary_amount': 'Summa',
    'create_operation_summary_rate': 'Kurs',
    'create_operation_summary_total': 'Jami',
    'create_operation_client_info': "Mijoz haqida ma'lumot",
    'create_operation_client_name': "Mijoz ismi (ixtiyoriy)",
    'create_operation_client_company': 'Kompaniya (ixtiyoriy)',
    'create_operation_comment_label': 'Izoh',
    'create_operation_comment_optional': 'Izoh (ixtiyoriy)',
    'create_operation_save': "O'zgarishlarni saqlash",
    'create_operation_create': 'Operatsiyani yaratish',
    'operations_filter_empty': 'Filtrlash parametrlarini o\'zgartirishga harakat qiling',
    'operations_empty_action': 'Birinchi operatsiyani yaratish uchun quyidagi tugmani bosing',
    'operations_cancel_title': 'Operatsiyani bekor qilish',
    'operations_cancel_confirm': '№{number} operatsiyani bekor qilish?',
    'operations_cancel_button': 'Bekor qilish',
    'operations_cancel_confirm_button': 'Bekor qilishni tasdiqlash',
    'operations_cancel_success': 'Operatsiya bekor qilindi',
    'operations_cancel_error': 'Operatsiyani bekor qilishda xato',
    'operations_no_results': 'Operatsiyalar yo\'q',
    'operations_filter_currency_title': 'Valyuta bo\'yicha filtrlash',
    'cash_no_balances': 'Balanslar yo\'q',
    'cash_no_balances_desc': 'Smenani ochganingizdan va birinchi operatsiyalarni amalga oshirganingizdan keyin balanslar paydo bo\'ladi',
    'close_register_success': 'Smena muvaffaqiyatli yopildi',
    'close_register_error': 'Smenani yopishda xato',
    'close_register_title': 'Smenani yopish',
    'close_register_loading': 'Kun yakuni yuklanmoqda...',
    'close_register_summary': 'Kun yakuni',
    'close_register_total_ops': 'Jami operatsiyalar',
    'close_register_buys': 'Sotib olishlar',
    'close_register_sells': 'Sotishlar',
    'close_register_turnover': 'Aylanma: {amount}',
    'close_register_cancelled': 'Bekor qilingan: {count}',
    'close_register_enter_balances': 'Valyutalar bo\'yicha haqiqiy qoldiqlarni kiriting',
    'close_register_required': 'Majburiy maydon',
    'close_register_invalid': "Noto'g'ri summa",
    'close_register_comment': 'Izoh (ixtiyoriy)',
    'close_register_cancel': 'Bekor qilish',
    'close_register_confirm': 'Smenani yopish',
    'open_register_need_balance': 'Kamida bitta qoldiq kiriting',
    'open_register_success': 'Smena muvaffaqiyatli ochildi',
    'open_register_error': 'Smenani ochishda xato',
    'open_register_title': 'Smenani ochish',
    'open_register_hint': 'Valyutalar bo\'yicha boshlang\'ich qoldiqlarni kiriting',
    'open_register_invalid': "Noto'g'ri summa",
    'open_register_comment': 'Izoh (ixtiyoriy)',
    'open_register_cancel': 'Bekor qilish',
    'open_register_confirm': 'Smenani ochish',
    'transaction_select_currency': 'Valyutani tanlang',
    'transaction_success': 'Tranzaksiya muvaffaqiyatli yaratildi',
    'transaction_error': 'Tranzaksiyani yaratishda xato',
    'transaction_title': 'Tranzaksiya',
    'transaction_deposit': 'Kiritish',
    'transaction_withdrawal': 'Chiqarish',
    'transaction_currency': 'Valyuta',
    'transaction_currency_placeholder': 'Valyutani tanlang',
    'transaction_amount': 'Summa',
    'transaction_amount_required': 'Summani kiriting',
    'transaction_amount_invalid': "Noto'g'ri summa",
    'transaction_comment': 'Izoh (ixtiyoriy)',
    'transaction_cancel': 'Bekor qilish',
    'transaction_create': 'Yaratish',
    'currencies_empty': "Valyuta kurslari ma'lumot yuklangandan keyin paydo bo'ladi",
    'currencies_total': 'Jami',
    'currencies_active': 'Faol',
    'currencies_with_rates': 'Kurslar bilan',
    'currencies_edit_rates': 'Kurslarni tahrirlash',
    'currencies_active_status': 'Faol',
    'currencies_inactive_status': 'Faol emas',
    'currencies_no_rates': 'Kurslar o\'rnatilmagan',
    'currencies_no_rates_short': 'Kurslar ko\'rsatilmagan',
    'currencies_rate_required': 'Kursni kiriting',
    'currencies_rate_invalid': "Noto'g'ri son",
    'analytics_operations': 'Operatsiyalar',
    'analytics_turnover_short': 'Aylanma',
    'analytics_buys_sells_short': 'Sotib olishlar/Sotishlar',
    'analytics_clients_short': 'Mijozlar',
    'analytics_operations_today_short': 'Bugungi operatsiyalar',
    'analytics_turnover_today': 'Bugungi aylanma',
    'analytics_buys_sells_today': 'Sotib olishlar / Sotishlar',
    'analytics_clients_today': 'Mijozlar',
    'analytics_period_7d': '7 kun',
    'analytics_period_14d': '14 kun',
    'analytics_period_30d': '30 kun',
    'analytics_ops_count': '{count} op.',
    'analytics_available': 'Mavjud: {balance}',
    'charts_no_data_period': 'Davr uchun ma\'lumot yo\'q',
    'charts_tooltip_buy_sell': "Sotib olish: {buy} • Sotish: {sell}",
    'charts_no_data': "Ma'lumot yo'q",
    'charts_ops_turnover': 'Operatsiyalar: {ops}\nAylanma: {turnover}',
    'charts_no_profitability': 'Daromadlilik haqida ma\'lumot yo\'q',
    'charts_profit': 'Foyda: {spread}\nMarja: {margin}%',
    'reports_cashier_shift': 'Kassir smenasi bo\'yicha hisobot',
    'reports_cashier_shift_desc': 'PDF-hisobot: qoldiqlar, operatsiyalar, smena yakuni',
    'settings_pin_6_digits': 'PIN-kod 6 raqamdan iborat bo\'lishi kerak',
    'settings_pin_mismatch': 'PIN-kodlar mos kelmaydi',
    'settings_pin_set': 'PIN-kod o\'rnatildi',
    'settings_pin_removed': 'PIN-kod o\'chirildi',
    'settings_pin_new': 'Yangi PIN-kod',
    'settings_pin_confirm': 'PIN-kodni tasdiqlash',
    'settings_pin_delete': 'PIN o\'chirish',
    'settings_pin_save': 'Saqlash',
    'settings_support_message': 'Salom! Menga My Exchange ilovasi bilan yordam kerak.',
    'entity_operation_type_buy': 'Sotib olish',
    'entity_operation_type_sell': 'Sotish',
    'entity_operation_status_active': 'Faol',
    'entity_operation_status_cancelled': 'Bekor qilingan',
    'entity_operation_status_partial': 'Qisman bekor qilingan',
    'entity_user_role_cashier': 'Kassir',
    'entity_user_role_senior_cashier': 'Katta kassir',
    'entity_user_role_admin': 'Administrator',
    'entity_transaction_type_deposit': 'Naqd pul kiritish',
    'entity_transaction_type_withdrawal': 'Naqd pul chiqarish',
    'entity_transaction_type_inkassation': 'Inkassatsiya',

    
    'onboarding_skip': "O'tkazib yuborish",
    'onboarding_next': 'Keyingi',
    'onboarding_get_started': 'Boshlash',
    'onboarding_welcome_title': "My Exchange ga xush kelibsiz",
    'onboarding_welcome_desc': 'Valyuta ayirboshlash operatsiyalarini tez va samarali boshqaring. Valyuta kurslarini kuzating, kassani yuriting va foydani tahlil qiling.',
    'onboarding_operations_title': 'Operatsiyalar va kassa',
    'onboarding_operations_desc': 'Valyuta sotib olish va sotish operatsiyalarini yarating, kassa smenalarini boshqaring va pul harakatini real vaqtda kuzating.',
    'onboarding_analytics_title': 'Analitika va hisobotlar',
    'onboarding_analytics_desc': "Foydani, ommabop valyutalarni kuzating va to'liq hisobotlarni bir tugma bilan yuklab oling.",
  };

  
  static const Map<String, String> _uzCyrillic = {
    
    'app_name': 'My Exchange',
    'app_title': 'Менинг Айирбошлаш',

    
    'nav_operations': 'Операциялар',
    'nav_cash': 'Касса',
    'nav_currencies': 'Валюталар',
    'nav_analytics': 'Аналитика',
    'nav_settings': 'Профиль',

    
    'login_title': 'Тизимга кириш',
    'login_username': 'Фойдаланувчи номи',
    'login_password': 'Парол',
    'login_button': 'Кириш',
    'login_error': 'Кириш хатоси',
    'login_username_required': 'Фойдаланувчи номини киритинг',
    'login_password_required': 'Паролни киритинг',
    'login_password_min': 'Парол камида 6 та белгидан иборат бўлиши керак',
    'login_version': 'Версия',
    'login_biometric': 'Touch ID / Face ID орқали кириш',
    'login_biometric_error': 'Биометрик аутентификация мавжуд эмас',
    'login_biometric_failed': 'Биометрия орқали кириш муваффақиятсиз',
    'login_biometric_save': 'Тез кириш учун эслаб қолиш',
    'login_biometric_reason': 'Иловага кириш учун шахсингизни тасдиқланг',

    
    'settings_title': 'Профиль ва созламалар',
    'settings_profile': 'Профиль',
    'settings_user_info': 'Фойдаланувчи маълумотлари',
    'settings_role': 'Лавозим',
    'settings_email': 'Email',
    'settings_phone': 'Телефон',
    'settings_language': 'Тил',
    'settings_language_ru': 'Русский',
    'settings_language_kg': 'Кыргызча',
    'settings_language_en': 'English',
    'settings_language_uz': "O'zbekcha",
    'settings_language_uzCyrillic': 'Ўзбекча',
    'settings_app_version': 'Илова версияси',
    'settings_logout': 'Чиқиш',
    'settings_logout_confirm': 'Чиқишни хохлайсизми?',
    'settings_logout_confirm_desc':
        'Қайта кириш учун логин ва парол керак бўлади.',
    'settings_cancel': 'Бекор қилиш',
    'settings_confirm': 'Ҳа, чиқиш',
    'settings_privacy_policy': 'Махфийлик сиёсати',
    'settings_contact_support': 'Қўллаб-қувватлаш',
    'settings_delete_account': 'Аккаунтни ўчириш',
    'settings_delete_account_desc':
        'Аккаунтингизни ва барча маълумотларни ўчириш сўровини юбориш.',
    'settings_delete_account_confirm':
        'Сўров юборилди. Тез орада сиз билан боғланамиз.',
    'settings_theme': 'Мавзу',
    'settings_theme_light': 'Ёруғ',
    'settings_theme_dark': 'Қоронғи',
    'settings_pin_code': 'PIN-код',
    'settings_pin_code_desc': 'Иловага кириш учун PIN-код ўрнатиш',
    'settings_biometric_login': 'Биометрик кириш',
    'settings_biometric_login_desc':
        'Тез кириш учун Touch ID / Face ID дан фойдаланиш',
    'lock_title': 'PIN-кодни киритинг',
    'lock_subtitle': 'Иловани очиш учун PIN-кодни киритинг',
    'lock_biometric': 'Touch ID / Face ID',
    'lock_biometric_reason': 'Иловага кириш учун шахсингизни тасдиқланг',
    'lock_biometric_failed': 'Биометрия хатоси. PIN-кодни киритинг',
    'lock_or': 'ёки',
    'settings_support_email': 'salievyt@gmail.com',
    'settings_support_chat': 'WhatsApp, Telegram',
    'settings_support_title': 'Қўллаб-қувватлаш билан боғланиш',
    'settings_support_description': 'Қулай алоқа усулини танланг',
    'settings_privacy_note':
        '«Чиқиш» тугмасини босиш орқали сиз жорий сеансни якунлайсиз.',

    
    'operations_title': 'Операциялар',
    'operations_create': 'Операция',
    'operations_empty': 'Операциялар йўқ',
    'operations_load': 'Юклаш',
    'operations_today': 'Бугун',
    'operations_buys': 'Харидлар',
    'operations_sells': 'Сотувлар',
    'operations_buy': 'Харид',
    'operations_sell': 'Сотув',
    'operations_search': 'Рақам, мижоз номи бўйича қидириш...',
    'operations_search_hint': 'Операция рақами, мижоз номи',
    'operations_filter_type': 'Тури',
    'operations_filter_all': 'Барчаси',
    'operations_filter_period': 'Давр',
    'operations_filter_period_today': 'Бугун',
    'operations_filter_period_week': 'Ҳафта',
    'operations_filter_period_month': 'Ой',
    'operations_filter_period_all': 'Барча вақт',
    'operations_filter_sort': 'Саралаш',
    'operations_filter_period_custom': 'Ўз даври',
    'operations_filter_currency': 'Валюта',
    'operations_filter_currency_all': 'Барча валюталар',
    'operations_columns': 'Устунлар',
    'operations_columns_1': '1 устун',
    'operations_columns_2': '2 устун',
    'operations_filter_date_from': 'Дан',
    'operations_filter_date_to': 'Гача',
    'operations_filter_date_apply': 'Қўллаш',
    'operations_edit': 'Таҳрирлаш',
    'operations_save': 'Сақлаш',
    'operations_edit_title': 'Операцияни таҳрирлаш',
    'operations_edit_success': 'Операция янгиланди',
    'operations_rate': 'Айирбошлаш курси',
    'operations_total': 'Бериладиган умумий сумма',
    'operations_amount': 'Валюта суммаси',
    'operations_filter_sort_newest': 'Янги',
    'operations_filter_sort_oldest': 'Эски',
    'operations_filter_sort_amount_asc': 'Сумма ↑',
    'operations_filter_sort_amount_desc': 'Сумма ↓',
    'operations_clear_filters': 'Фильтрларни тозалаш',
    'operations_found': 'Топилди:',

    
    'cash_title': 'Касса',
    'cash_balances': 'Қолдиқлар',
    'cash_register_open': 'Смена очик',
    'cash_register_closed': 'Смена очик эмас',
    'cash_register_open_desc': 'Ишни бошлаш учун сменани очинг',
    'cash_register_close': 'Сменани ёпиш',
    'cash_open_shift': 'Сменани очиш',
    'cash_transaction': 'Транзакция',
    'cash_available': 'Мавжуд',
    'cash_reserved': 'Заҳираланган',
    'cash_cashier': 'Кассир',
    'cash_opened_at': 'Очилган',
    'cash_opening_balance': 'Бошланғич қолдиқлар',
    'cash_no_data': 'Маълумот йўқ',

    
    'currencies_title': 'Валюталар',
    'currencies_buy': 'Харид',
    'currencies_sell': 'Сотув',

    
    'analytics_title': 'Аналитика',
    'analytics_no_data': 'Кўрсатиш учун маълумот йўқ',
    'analytics_no_data_desc': 'Операциялардан сўнг статистика пайдо бўлади',
    'analytics_overall': 'Умумий статистика',
    'analytics_operations_today': 'Бугунги операциялар',
    'analytics_buys_sells': 'Харидлар / Сотувлар',
    'analytics_turnover': 'Айланма (сўм)',
    'analytics_clients': 'Мижозлар',
    'analytics_rates': 'Валюта курслари',
    'analytics_daily_chart': 'Кунлар бўйича операциялар',
    'analytics_popular_currencies': 'Оммабоп валюталар',
    'analytics_profitability': 'Даромадлилик (маржа %)',
    'analytics_cashiers': 'Кассирлар',
    'analytics_cash_balances': 'Кассадаги қолдиқлар',
    'analytics_reports': 'Ҳисоботлар',

    
    'reports_title': 'Ҳисоботлар',
    'reports_subtitle': 'Ҳисоботларни юклаб олиш',
    'reports_desc':
        'Маълумотларни CSV, Excel ёки PDF форматида бир тугма билан экспорт қилиш',
    'reports_daily': 'Кунлик ҳисобот',
    'reports_daily_desc': 'Кун якуни: операциялар, айланма, қолдиқлар',
    'reports_monthly': 'Ойлик ҳисобот',
    'reports_monthly_desc': 'Ой ичидаги кунлар бўйича статистика',
    'reports_operations': 'Операцияларни экспорт қилиш',
    'reports_operations_desc': 'Барча операциялар жадвалда',
    'reports_cash': 'Кассани экспорт қилиш',
    'reports_cash_desc': 'Кассадаги пул ҳаракати',
    'reports_download': 'Юклаб олиш',
    'reports_generating': 'Ҳисобот тайёрланмоқда...',
    'reports_saved': 'Файл сақланди',
    'reports_saved_desc':
        'Файл фойдаланишга тайёр. Юбориш ёки сақлаш учун «Улашиш» тугмасини босинг.',
    'reports_open_share': 'Улашиш / Сақлаш',

    
    'general_retry': 'Қайта уриниш',
    'general_refresh': 'Янгилаш',
    'general_loading': 'Юкланмоқда...',
    'general_error': 'Хато',
    'general_success': 'Муваффақиятли',
    'general_close': 'Ёпиш',
    'general_ops': 'оп.',
    'general_today': 'Бугун',
    'general_yesterday': 'Кеча',
    'general_just_now': 'Ҳозиргина',
    'general_min_ago': 'дақ. олдин',
    'general_hours_ago': 'соат. олдин',
    'general_days_ago': 'кун. олдин',
    'general_som': 'сўм',

    'error_retry': 'Қайта уриниш',
    'error_close': 'Ёпиш',
    'footer_made_with_love': 'Севги билан қилинган',
    'update_available': 'Янгиланиш мавжуд',
    'update_version': 'Версия {version}',
    'update_required': 'Мажбурий янгиланиш',
    'update_whats_new': 'Нима янги:',
    'update_link': 'Янгиланиш ҳаволаси: {url}',
    'update_now': 'Ҳозир янгилаш',
    'update_later': 'Кейинроқ',
    'lock_wrong_pin': 'Нотўғри PIN-код',
    'operation_card_cancel': 'Бекор қилиш',
    'operation_card_edit': 'Таҳрирлаш',
    'operation_card_rate': 'Курс: {rate}',
    'operation_card_total': 'Жами: {amount}',
    'operation_detail_edit_tooltip': 'Таҳрирлаш',
    'operation_detail_amount': 'Операция суммаси',
    'operation_detail_rate_label': 'Курс',
    'operation_detail_total_som': 'Сўмда жами',
    'operation_detail_client': 'Мижоз',
    'operation_detail_client_name': 'Исми',
    'operation_detail_client_company': 'Компания',
    'operation_detail_details': 'Батафсил маълумот',
    'operation_detail_cashier': 'Кассир',
    'operation_detail_created': 'Яратилган сана',
    'operation_detail_updated': 'Сўнгги ўзгартириш',
    'operation_detail_id': 'Операция ID',
    'operation_detail_comment': 'Изоҳ',
    'operation_detail_edit_button': 'Операцияни таҳрирлаш',
    'operation_detail_status': 'Ҳолати',
    'operation_detail_status_created': 'Операция яратилди',
    'operation_detail_status_created_sub': 'Тизимда ўтказилди',
    'operation_detail_status_executed': 'Бажарилди',
    'operation_detail_status_cancelled': 'Бекор қилинди',
    'operation_detail_status_partial': 'Қисман бекор қилинди',
    'operation_detail_status_executed_sub': 'Операция муваффақиятли якунланди',
    'operation_detail_status_cancelled_sub': 'Операция бекор қилинди',
    'operation_detail_status_partial_sub': 'Бир қисми бекор қилинди',
    'create_operation_select_currency': 'Валютани танланг',
    'create_operation_insufficient_kgs': 'Кассада сўм (KGS) етарли эмас. Мавжуд: {balance}, талаб қилинади: {required}',
    'create_operation_insufficient_currency': 'Кассада {currency} етарли эмас. Мавжуд: {balance}',
    'create_operation_success_updated': 'Операция янгиланди',
    'create_operation_error_update': 'Операцияни янгилашда хато',
    'create_operation_success_created': 'Операция муваффақиятли яратилди',
    'create_operation_error_create': 'Операцияни яратишда хато',
    'create_operation_title_edit': 'Операцияни таҳрирлаш',
    'create_operation_title_new': 'Янги операция',
    'create_operation_type': 'Операция тури',
    'create_operation_currency': 'Валюта',
    'create_operation_currency_select': 'Валютани танланг',
    'create_operation_params': 'Операция параметрлари',
    'create_operation_params_hint': 'Ҳар қандай иккита майдонни ўзгартириш учинчисини автоматик қайта ҳисоблайди',
    'create_operation_amount_buy_label': 'Сотиб олиш суммаси (валюта)',
    'create_operation_amount_sell_label': 'Сотиш суммаси (валюта)',
    'create_operation_amount_required': 'Суммани киритинг',
    'create_operation_amount_invalid': 'Нотўғри сумма',
    'create_operation_rate_label': 'Айирбошлаш курси',
    'create_operation_rate_required': 'Курсни киритинг',
    'create_operation_rate_invalid': 'Нотўғри курс',
    'create_operation_total_label': 'Бериладиган умумий сумма (сўм)',
    'create_operation_total_required': 'Умумий суммани киритинг',
    'create_operation_total_invalid': 'Нотўғри сумма',
    'create_operation_summary_amount': 'Сумма',
    'create_operation_summary_rate': 'Курс',
    'create_operation_summary_total': 'Жами',
    'create_operation_client_info': 'Мижоз ҳақида маълумот',
    'create_operation_client_name': 'Мижоз исми (ихтиёрий)',
    'create_operation_client_company': 'Компания (ихтиёрий)',
    'create_operation_comment_label': 'Изоҳ',
    'create_operation_comment_optional': 'Изоҳ (ихтиёрий)',
    'create_operation_save': 'Ўзгаришларни сақлаш',
    'create_operation_create': 'Операцияни яратиш',
    'operations_filter_empty': 'Фильтрлаш параметрларини ўзгартиришга ҳаракат қилинг',
    'operations_empty_action': 'Биринчи операцияни яратиш учун қуйидаги тугмани босинг',
    'operations_cancel_title': 'Операцияни бекор қилиш',
    'operations_cancel_confirm': '№{number} операцияни бекор қилиш?',
    'operations_cancel_button': 'Бекор қилиш',
    'operations_cancel_confirm_button': 'Бекор қилишни тасдиқлаш',
    'operations_cancel_success': 'Операция бекор қилинди',
    'operations_cancel_error': 'Операцияни бекор қилишда хато',
    'operations_no_results': 'Операциялар йўқ',
    'operations_filter_currency_title': 'Валюта бўйича фильтрлаш',
    'cash_no_balances': 'Баланслар йўқ',
    'cash_no_balances_desc': 'Сменани очганингиздан ва биринчи операцияларни амалга оширганингиздан кейин баланслар пайдо бўлади',
    'close_register_success': 'Смена муваффақиятли ёпилди',
    'close_register_error': 'Сменани ёпишда хато',
    'close_register_title': 'Сменани ёпиш',
    'close_register_loading': 'Кун якуни юкланмоқда...',
    'close_register_summary': 'Кун якуни',
    'close_register_total_ops': 'Жами операциялар',
    'close_register_buys': 'Сотиб олишлар',
    'close_register_sells': 'Сотишлар',
    'close_register_turnover': 'Айланма: {amount}',
    'close_register_cancelled': 'Бекор қилинган: {count}',
    'close_register_enter_balances': 'Валюталар бўйича ҳақиқий қолдиқларни киритинг',
    'close_register_required': 'Мажбурий майдон',
    'close_register_invalid': 'Нотўғри сумма',
    'close_register_comment': 'Изоҳ (ихтиёрий)',
    'close_register_cancel': 'Бекор қилиш',
    'close_register_confirm': 'Сменани ёпиш',
    'open_register_need_balance': 'Камида битта қолдиқ киритинг',
    'open_register_success': 'Смена муваффақиятли очилди',
    'open_register_error': 'Сменани очишда хато',
    'open_register_title': 'Сменани очиш',
    'open_register_hint': 'Валюталар бўйича бошланғич қолдиқларни киритинг',
    'open_register_invalid': 'Нотўғри сумма',
    'open_register_comment': 'Изоҳ (ихтиёрий)',
    'open_register_cancel': 'Бекор қилиш',
    'open_register_confirm': 'Сменани очиш',
    'transaction_select_currency': 'Валютани танланг',
    'transaction_success': 'Транзакция муваффақиятли яратилди',
    'transaction_error': 'Транзакцияни яратишда хато',
    'transaction_title': 'Транзакция',
    'transaction_deposit': 'Киритиш',
    'transaction_withdrawal': 'Чиқариш',
    'transaction_currency': 'Валюта',
    'transaction_currency_placeholder': 'Валютани танланг',
    'transaction_amount': 'Сумма',
    'transaction_amount_required': 'Суммани киритинг',
    'transaction_amount_invalid': 'Нотўғри сумма',
    'transaction_client_name': 'Мизож (ихтиёрий)',
    'transaction_client_company': 'Компания (ихтиёрий)',
    'transaction_rate': 'Курс (чет эл валютаси бўлса)',
    'transaction_rate_hint': 'Ихтиёрий',
    'transaction_comment': 'Изоҳ (ихтиёрий)',
    'transaction_cancel': 'Бекор қилиш',
    'transaction_create': 'Яратиш',
    'currencies_empty': 'Валюта курслари маълумот юклангандан кейин пайдо бўлади',
    'currencies_total': 'Жами',
    'currencies_active': 'Фаол',
    'currencies_with_rates': 'Курслар билан',
    'currencies_edit_rates': 'Курсларни таҳрирлаш',
    'currencies_active_status': 'Фаол',
    'currencies_inactive_status': 'Фаол эмас',
    'currencies_no_rates': 'Курслар ўрнатилмаган',
    'currencies_no_rates_short': 'Курслар кўрсатилмаган',
    'currencies_rate_required': 'Курсни киритинг',
    'currencies_rate_invalid': 'Нотўғри сон',
    'analytics_operations': 'Операциялар',
    'analytics_turnover_short': 'Айланма',
    'analytics_buys_sells_short': 'Сотиб олишлар/Сотишлар',
    'analytics_clients_short': 'Мижозлар',
    'analytics_operations_today_short': 'Бугунги операциялар',
    'analytics_turnover_today': 'Бугунги айланма',
    'analytics_buys_sells_today': 'Сотиб олишлар / Сотишлар',
    'analytics_clients_today': 'Мижозлар',
    'analytics_period_7d': '7 кун',
    'analytics_period_14d': '14 кун',
    'analytics_period_30d': '30 кун',
    'analytics_ops_count': '{count} оп.',
    'analytics_available': 'Мавжуд: {balance}',
    'charts_no_data_period': 'Давр учун маълумот йўқ',
    'charts_tooltip_buy_sell': 'Сотиб олиш: {buy} • Сотиш: {sell}',
    'charts_no_data': 'Маълумот йўқ',
    'charts_ops_turnover': 'Операциялар: {ops}\nАйланма: {turnover}',
    'charts_no_profitability': 'Даромадлилик ҳақида маълумот йўқ',
    'charts_profit': 'Фойда: {spread}\nМаржа: {margin}%',
    'reports_cashier_shift': 'Кассир сменаси бўйича ҳисобот',
    'reports_cashier_shift_desc': 'PDF-ҳисобот: қолдиқлар, операциялар, смена якуни',
    'settings_pin_6_digits': 'PIN-код 6 рақамдан иборат бўлиши керак',
    'settings_pin_mismatch': 'PIN-кодлар мос келмайди',
    'settings_pin_set': 'PIN-код ўрнатилди',
    'settings_pin_removed': 'PIN-код ўчирилди',
    'settings_pin_new': 'Янги PIN-код',
    'settings_pin_confirm': 'PIN-кодни тасдиқлаш',
    'settings_pin_delete': 'PIN ўчириш',
    'settings_pin_save': 'Сақлаш',
    'settings_support_message': 'Салом! Менга My Exchange иловаси билан ёрдам керак.',
    'entity_operation_type_buy': 'Сотиб олиш',
    'entity_operation_type_sell': 'Сотиш',
    'entity_operation_status_active': 'Фаол',
    'entity_operation_status_cancelled': 'Бекор қилинган',
    'entity_operation_status_partial': 'Қисман бекор қилинган',
    'entity_user_role_cashier': 'Кассир',
    'entity_user_role_senior_cashier': 'Катта кассир',
    'entity_user_role_admin': 'Администратор',
    'entity_transaction_type_deposit': 'Нақд пул киритиш',
    'entity_transaction_type_withdrawal': 'Нақд пул чиқариш',
    'entity_transaction_type_inkassation': 'Инкассация',

    
    'onboarding_skip': 'Ўтказиб юбориш',
    'onboarding_next': 'Кейинги',
    'onboarding_get_started': 'Бошлаш',
    'onboarding_welcome_title': 'My Exchange га хуш келибсиз',
    'onboarding_welcome_desc': 'Валюта айирбошлаш операцияларини тез ва самарали бошқаринг. Валюта курсларини кузатинг, кассани юритинг ва фойдани таҳлил қилинг.',
    'onboarding_operations_title': 'Операциялар ва касса',
    'onboarding_operations_desc': 'Валюта сотиб олиш ва сотиш операцияларини яратинг, касса сменаларини бошқаринг ва пул ҳаракатини реал вақтда кузатинг.',
    'onboarding_analytics_title': 'Аналитика ва ҳисоботлар',
    'onboarding_analytics_desc': 'Фойдани, оммабоп валюталарни кузатинг ва тўлиқ ҳисоботларни бир тугма билан юклаб олинг.',
  };
}
