/// Localized strings for the app.
/// Keys are the same across languages; values are the translations.
class AppStrings {
  const AppStrings._();

  /// All supported locales.
  static const List<String> supportedLocales = [
    'ru',
    'ky',
    'en',
    'uz',
    'uz_Cyrl',
  ];
  static const String defaultLocale = 'ru';

  /// Map of locale -> (string key -> translated value).
  static const Map<String, Map<String, String>> _strings = {
    'ru': _ru,
    'ky': _kg,
    'en': _en,
    'uz': _uz,
    'uz_Cyrl': _uzCyrillic,
  };

  /// Returns the translated string for [key] in [locale].
  /// Falls back to Russian, then to the key itself.
  static String t(String key, {String locale = 'ru'}) {
    return _strings[locale]?[key] ?? _strings['ru']?[key] ?? key;
  }

  /// Convenience: get all key-value pairs for a locale.
  static Map<String, String> forLocale(String locale) {
    return _strings[locale] ?? _strings['ru']!;
  }

  
  static const Map<String, String> _ru = {
    
    'app_name': 'My Exchange',
    'app_title': 'Моя волюта',

    
    'nav_operations': 'Операции',
    'nav_cash': 'Касса',
    'nav_currencies': 'Валюты',
    'nav_analytics': 'Аналитика',
    'nav_settings': 'Профиль',

    
    'login_title': 'Вход в систему',
    'login_username': 'Имя пользователя',
    'login_password': 'Пароль',
    'login_button': 'Войти',
    'login_error': 'Ошибка входа',
    'login_username_required': 'Введите имя пользователя',
    'login_password_required': 'Введите пароль',
    'login_password_min': 'Пароль должен быть не менее 6 символов',
    'login_version': 'Версия',
    'login_biometric': 'Войти по Touch ID / Face ID',
    'login_biometric_error': 'Биометрическая аутентификация недоступна',
    'login_biometric_failed': 'Не удалось выполнить вход по биометрии',
    'login_biometric_save': 'Запомнить для быстрого входа',
    'login_biometric_reason': 'Подтвердите личность для входа в приложение',

    
    'settings_title': 'Профиль и настройки',
    'settings_profile': 'Профиль',
    'settings_user_info': 'Информация о пользователе',
    'settings_role': 'Должность',
    'settings_email': 'Email',
    'settings_phone': 'Телефон',
    'settings_language': 'Язык',
    'settings_language_ru': 'Русский',
    'settings_language_kg': 'Кыргызча',
    'settings_language_en': 'English',
    'settings_language_uz': "O'zbekcha",
    'settings_language_uzCyrillic': 'Ўзбекча',
    'settings_app_version': 'Версия приложения',
    'settings_logout': 'Выйти',
    'settings_logout_confirm': 'Вы уверены, что хотите выйти?',
    'settings_logout_confirm_desc':
        'Для повторного входа потребуется ввести логин и пароль.',
    'settings_cancel': 'Отмена',
    'settings_confirm': 'Да, выйти',
    'settings_privacy_policy': 'Политика конфиденциальности',
    'settings_contact_support': 'Связаться с поддержкой',
    'settings_delete_account': 'Запросить удаление аккаунта',
    'settings_delete_account_desc':
        'Отправить запрос на удаление вашего аккаунта и всех связанных данных.',
    'settings_delete_account_confirm':
        'Запрос отправлен. С вами свяжутся в ближайшее время.',
    'settings_theme': 'Тема оформления',
    'settings_theme_light': 'Светлая',
    'settings_theme_dark': 'Тёмная',
    'settings_pin_code': 'PIN-код',
    'settings_pin_code_desc': 'Установить PIN-код для входа в приложение',
    'settings_biometric_login': 'Вход по биометрии',
    'settings_biometric_login_desc':
        'Использовать Touch ID / Face ID для быстрого входа',

    
    'lock_title': 'Введите PIN-код',
    'lock_subtitle': 'Введите PIN-код для разблокировки приложения',
    'lock_biometric': 'Touch ID / Face ID',
    'lock_biometric_reason': 'Подтвердите личность для входа в приложение',
    'lock_biometric_failed': 'Ошибка биометрии. Введите PIN-код',
    'lock_or': 'или',

    'settings_support_email': 'salievyt@gmail.com',
    'settings_support_chat': 'WhatsApp, Telegram',
    'settings_support_title': 'Связаться с поддержкой',
    'settings_support_description': 'Выберите удобный способ связи',
    'settings_privacy_note': 'Нажимая «Выйти», вы завершаете текущую сессию.',

    
    'operations_title': 'Операции',
    'operations_create': 'Операция',
    'operations_empty': 'Нет операций',
    'operations_load': 'Загрузить',
    'operations_today': 'Сегодня',
    'operations_buys': 'Покупки',
    'operations_sells': 'Продажи',
    'operations_buy': 'Покупка',
    'operations_sell': 'Продажа',
    'operations_search': 'Поиск по номеру, клиенту...',
    'operations_search_hint': 'Номер операции, имя клиента',
    'operations_filter_type': 'Тип',
    'operations_filter_all': 'Все',
    'operations_filter_period': 'Период',
    'operations_filter_period_today': 'Сегодня',
    'operations_filter_period_week': 'Неделя',
    'operations_filter_period_month': 'Месяц',
    'operations_filter_period_custom': 'Свой период',
    'operations_filter_period_all': 'Всё время',
    'operations_filter_sort': 'Сортировка',
    'operations_filter_currency': 'Валюта',
    'operations_filter_currency_all': 'Все валюты',
    'operations_columns': 'Колонки',
    'operations_columns_1': '1 колонка',
    'operations_columns_2': '2 колонки',
    'operations_filter_date_from': 'От',
    'operations_filter_date_to': 'До',
    'operations_filter_date_apply': 'Применить',
    'operations_edit': 'Редактировать',
    'operations_save': 'Сохранить',
    'operations_edit_title': 'Редактирование операции',
    'operations_edit_success': 'Операция обновлена',
    'operations_rate': 'Курс обмена',
    'operations_total': 'Итого к выдаче',
    'operations_amount': 'Сумма валюты',
    'operations_filter_sort_newest': 'Новые',
    'operations_filter_sort_oldest': 'Старые',
    'operations_filter_sort_amount_asc': 'Сумма ↑',
    'operations_filter_sort_amount_desc': 'Сумма ↓',
    'operations_clear_filters': 'Сбросить фильтры',
    'operations_found': 'Найдено:',

    
    'cash_title': 'Касса',
    'cash_balances': 'Остатки',
    'cash_register_open': 'Смена открыта',
    'cash_register_closed': 'Смена не открыта',
    'cash_register_open_desc': 'Откройте смену для начала работы',
    'cash_register_close': 'Закрыть смену',
    'cash_open_shift': 'Открыть смену',
    'cash_transaction': 'Транзакция',
    'cash_available': 'Доступно',
    'cash_reserved': 'Зарезервировано',
    'cash_cashier': 'Кассир',
    'cash_opened_at': 'Открыта',
    'cash_no_data': 'Нет данных',

    
    'currencies_title': 'Валюты',
    'currencies_buy': 'Покупка',
    'currencies_sell': 'Продажа',

    
    'analytics_title': 'Аналитика',
    'analytics_no_data': 'Нет данных для отображения',
    'analytics_no_data_desc': 'Статистика появится после совершения операций',
    'analytics_overall': 'Общая статистика',
    'analytics_operations_today': 'Операций сегодня',
    'analytics_buys_sells': 'Покупок / Продаж',
    'analytics_turnover': 'Оборот (сом)',
    'analytics_clients': 'Клиентов',
    'analytics_rates': 'Курсы валют',
    'analytics_daily_chart': 'Операции по дням',
    'analytics_popular_currencies': 'Популярные валюты',
    'analytics_profitability': 'Рентабельность (маржа %)',
    'analytics_cashiers': 'Кассиры',
    'analytics_cash_balances': 'Остатки в кассе',
    'analytics_reports': 'Отчёты',

    
    'reports_title': 'Отчёты',
    'reports_subtitle': 'Скачать отчёты',
    'reports_desc':
        'Экспорт данных в формате CSV, Excel или PDF по нажатию одной кнопки',
    'reports_daily': 'Дневной отчёт',
    'reports_daily_desc': 'Итоги дня: операции, оборот, остатки',
    'reports_monthly': 'Месячный отчёт',
    'reports_monthly_desc': 'Статистика за месяц по дням',
    'reports_operations': 'Экспорт операций',
    'reports_operations_desc': 'Все операции за период в таблице',
    'reports_cash': 'Экспорт кассы',
    'reports_cash_desc': 'Движение денег по кассе',
    'reports_download': 'Скачать',
    'reports_generating': 'Формирование отчёта...',
    'reports_saved': 'Файл сохранён',
    'reports_saved_desc':
        'Файл готов к использованию. Нажмите «Поделиться», чтобы отправить или сохранить его.',
    'reports_open_share': 'Поделиться / Сохранить',

    
    'general_retry': 'Повторить',
    'general_refresh': 'Обновить',
    'general_loading': 'Загрузка...',
    'general_error': 'Ошибка',
    'general_success': 'Успешно',
    'general_close': 'Закрыть',
    'general_ops': 'оп.',
    'general_today': 'Сегодня',
    'general_yesterday': 'Вчера',
    'general_just_now': 'Только что',
    'general_min_ago': 'мин. назад',
    'general_hours_ago': 'ч. назад',
    'general_days_ago': 'дн. назад',
    'general_som': 'сом',
  };

  
  static const Map<String, String> _kg = {
    
    'app_name': 'My Exchange',
    'app_title': 'Моя волюта',

    
    'nav_operations': 'Операциялар',
    'nav_cash': 'Касса',
    'nav_currencies': 'Валюталар',
    'nav_analytics': 'Аналитика',
    'nav_settings': 'Профиль',

    
    'login_title': 'Системага кирүү',
    'login_username': 'Колдонуучу аты',
    'login_password': 'Сырсөз',
    'login_button': 'Кирүү',
    'login_error': 'Кирүү катасы',
    'login_username_required': 'Колдонуучу атын жазыңыз',
    'login_password_required': 'Сырсөздү жазыңыз',
    'login_password_min': 'Сырсөз кеминде 6 символ болушу керек',
    'login_version': 'Версия',
    'login_biometric': 'Touch ID / Face ID аркылуу кирүү',
    'login_biometric_error': 'Биометриялык аутентификация жеткиликтүү эмес',
    'login_biometric_failed': 'Биометрия аркылуу кирүү мүмкүн болгон жок',
    'login_biometric_save': 'Тез кирүү үчүн сактоо',
    'login_biometric_reason': 'Кирүү үчүн инсандыгыңызды тастыктаңыз',

    
    'settings_title': 'Профиль жана орнотуулар',
    'settings_profile': 'Профиль',
    'settings_user_info': 'Колдонуучу маалыматы',
    'settings_role': 'Кызматы',
    'settings_email': 'Email',
    'settings_phone': 'Телефон',
    'settings_language': 'Тил',
    'settings_language_ru': 'Орусча',
    'settings_language_kg': 'Кыргызча',
    'settings_language_en': 'English',
    'settings_language_uz': "O'zbekcha",
    'settings_language_uzCyrillic': 'Ўзбекча',
    'settings_app_version': 'Колдонмо версиясы',
    'settings_logout': 'Чыгуу',
    'settings_logout_confirm': 'Чыгууга ишенесизби?',
    'settings_logout_confirm_desc':
        'Кайра кирүү үчүн логин жана сырсөз керек болот.',
    'settings_cancel': 'Жокко чыгаруу',
    'settings_confirm': 'Ооба, чыгуу',
    'settings_privacy_policy': 'Купуялык саясаты',
    'settings_contact_support': 'Колдоо кызматы',
    'settings_delete_account': 'Аккаунтту жок кылуу',
    'settings_delete_account_desc':
        'Аккаунтуңузду жана бардык маалыматтарды жок кылуу өтүнүчүн жөнөтүү.',
    'settings_delete_account_confirm':
        'Өтүнүч жөнөтүлдү. Жакында сиз менен байланышабыз.',
    'settings_theme': 'Тема',
    'settings_theme_light': 'Жарык',
    'settings_theme_dark': 'Караңгы',
    'settings_pin_code': 'PIN-код',
    'settings_pin_code_desc': 'Колдонмого кирүү үчүн PIN-код орнотуу',
    'settings_biometric_login': 'Биометриялык кирүү',
    'settings_biometric_login_desc':
        'Тез кирүү үчүн Touch ID / Face ID колдонуу',
    'lock_title': 'PIN-кодду киргизиңиз',
    'lock_subtitle': 'Колдонмону ачуу үчүн PIN-кодду киргизиңиз',
    'lock_biometric': 'Touch ID / Face ID',
    'lock_biometric_reason': 'Кирүү үчүн инсандыгыңызды тастыктаңыз',
    'lock_biometric_failed': 'Биометрия катасы. PIN-кодду киргизиңиз',
    'lock_or': 'же',
    'settings_support_email': 'salievyt@gmail.com',
    'settings_support_chat': 'WhatsApp, Telegram',
    'settings_support_title': 'Колдоо кызматы менен байланышуу',
    'settings_support_description': 'Байланышуу үчүн ыңгайлуу ыкманы тандаңыз',
    'settings_privacy_note':
        '«Чыгуу» баскычын басуу менен, сиз учурдагы сессияны аяктайсыз.',

    
    'operations_title': 'Операциялар',
    'operations_create': 'Операция',
    'operations_empty': 'Операциялар жок',
    'operations_load': 'Жүктөө',
    'operations_today': 'Бүгүн',
    'operations_buys': 'Сатып алуулар',
    'operations_sells': 'Сатуулар',
    'operations_buy': 'Сатып алуу',
    'operations_sell': 'Сатуу',
    'operations_search': 'Номери, кардар аты боюнча издөө...',
    'operations_search_hint': 'Операция номери, кардардын аты',
    'operations_filter_type': 'Түрү',
    'operations_filter_all': 'Баары',
    'operations_filter_period': 'Мөөнөт',
    'operations_filter_period_today': 'Бүгүн',
    'operations_filter_period_week': 'Апта',
    'operations_filter_period_month': 'Ай',
    'operations_filter_period_all': 'Бардык убакыт',
    'operations_filter_sort': 'Иреттөө',
    'operations_filter_period_custom': 'Өз мөөнөтү',
    'operations_filter_currency': 'Валюта',
    'operations_filter_currency_all': 'Бардык валюталар',
    'operations_columns': 'Колонкалар',
    'operations_columns_1': '1 колонка',
    'operations_columns_2': '2 колонка',
    'operations_filter_date_from': 'Башталган күн',
    'operations_filter_date_to': 'Чейинки күн',
    'operations_filter_date_apply': 'Колдонуу',
    'operations_edit': 'Оңдоо',
    'operations_save': 'Сактоо',
    'operations_edit_title': 'Операцияны оңдоо',
    'operations_edit_success': 'Операция жаңыртылды',
    'operations_rate': 'Алмашуу курсу',
    'operations_total': 'Берүүчү жалпы сумма',
    'operations_amount': 'Валюта суммасы',
    'operations_filter_sort_newest': 'Жаңылары',
    'operations_filter_sort_oldest': 'Эскилери',
    'operations_filter_sort_amount_asc': 'Сумма ↑',
    'operations_filter_sort_amount_desc': 'Сумма ↓',
    'operations_clear_filters': 'Чыпкаларды тазалоо',
    'operations_found': 'Табылды:',

    
    'cash_title': 'Касса',
    'cash_balances': 'Калдыктар',
    'cash_register_open': 'Смена ачык',
    'cash_register_closed': 'Смена ачык эмес',
    'cash_register_open_desc': 'Ишти баштоо үчүн сменаны ачыңыз',
    'cash_register_close': 'Сменаны жабуу',
    'cash_open_shift': 'Сменаны ачуу',
    'cash_transaction': 'Транзакция',
    'cash_available': 'Жеткиликтүү',
    'cash_reserved': 'Резервделген',
    'cash_cashier': 'Кассир',
    'cash_opened_at': 'Ачылган',
    'cash_no_data': 'Маалымат жок',

    
    'currencies_title': 'Валюталар',
    'currencies_buy': 'Сатып алуу',
    'currencies_sell': 'Сатуу',

    
    'analytics_title': 'Аналитика',
    'analytics_no_data': 'Көрсөтүү үчүн маалымат жок',
    'analytics_no_data_desc': 'Операциялардан кийин статистика пайда болот',
    'analytics_overall': 'Жалпы статистика',
    'analytics_operations_today': 'Бүгүнкү операциялар',
    'analytics_buys_sells': 'Сатып алуулар / Сатуулар',
    'analytics_turnover': 'Жүгүртүү (сом)',
    'analytics_clients': 'Кардарлар',
    'analytics_rates': 'Валюта курстары',
    'analytics_daily_chart': 'Күндөр боюнча операциялар',
    'analytics_popular_currencies': 'Популярдуу валюталар',
    'analytics_profitability': 'Рентабелдүүлүк (маржа %)',
    'analytics_cashiers': 'Кассирлер',
    'analytics_cash_balances': 'Кассадагы калдыктар',
    'analytics_reports': 'Отчёты',

    
    'reports_title': 'Отчёттор',
    'reports_subtitle': 'Отчётторду жүктөө',
    'reports_desc':
        'Маалыматтарды CSV, Excel же PDF форматында бир баскыч менен экспорттоо',
    'reports_daily': 'Күндүк отчёт',
    'reports_daily_desc': 'Күндүн жыйынтыгы: операциялар, жүгүртүү, калдыктар',
    'reports_monthly': 'Айлык отчёт',
    'reports_monthly_desc': 'Ай ичиндеги күндөр боюнча статистика',
    'reports_operations': 'Операцияларды экспорттоо',
    'reports_operations_desc': 'Бардык операциялар таблицада',
    'reports_cash': 'Кассаны экспорттоо',
    'reports_cash_desc': 'Кассадагы акча кыймылы',
    'reports_download': 'Жүктөө',
    'reports_generating': 'Отчёт түзүлүүдө...',
    'reports_saved': 'Файл сакталды',
    'reports_saved_desc':
        'Файл колдонууга даяр. Жөнөтүү же сактоо үчүн «Бөлүшүү» баскычын басыңыз.',
    'reports_open_share': 'Бөлүшүү / Сактоо',

    
    'general_retry': 'Кайталоо',
    'general_refresh': 'Жаңыртуу',
    'general_loading': 'Жүктөлүүдө...',
    'general_error': 'Ката',
    'general_success': 'Ийгиликтүү',
    'general_close': 'Жабуу',
    'general_ops': 'оп.',
    'general_today': 'Бүгүн',
    'general_yesterday': 'Кечээ',
    'general_just_now': 'Жаңы эле',
    'general_min_ago': 'мүн. мурун',
    'general_hours_ago': 'саат. мурун',
    'general_days_ago': 'күн. мурун',
    'general_som': 'сом',
  };

  
  static const Map<String, String> _en = {
    
    'app_name': 'My Exchange',
    'app_title': 'My Exchange',

    
    'nav_operations': 'Operations',
    'nav_cash': 'Cash',
    'nav_currencies': 'Currencies',
    'nav_analytics': 'Analytics',
    'nav_settings': 'Profile',

    
    'login_title': 'Sign In',
    'login_username': 'Username',
    'login_password': 'Password',
    'login_button': 'Sign In',
    'login_error': 'Login failed',
    'login_username_required': 'Enter username',
    'login_password_required': 'Enter password',
    'login_password_min': 'Password must be at least 6 characters',
    'login_version': 'Version',
    'login_biometric': 'Sign in with Touch ID / Face ID',
    'login_biometric_error': 'Biometric authentication is not available',
    'login_biometric_failed': 'Biometric login failed',
    'login_biometric_save': 'Remember for quick login',
    'login_biometric_reason': 'Authenticate to sign in to the app',

    
    'settings_title': 'Profile & Settings',
    'settings_profile': 'Profile',
    'settings_user_info': 'User Information',
    'settings_role': 'Role',
    'settings_email': 'Email',
    'settings_phone': 'Phone',
    'settings_language': 'Language',
    'settings_language_ru': 'Русский',
    'settings_language_kg': 'Кыргызча',
    'settings_language_en': 'English',
    'settings_language_uz': "O'zbekcha",
    'settings_language_uzCyrillic': 'Ўзбекча',
    'settings_app_version': 'App Version',
    'settings_logout': 'Log Out',
    'settings_logout_confirm': 'Are you sure you want to log out?',
    'settings_logout_confirm_desc':
        'You will need to enter your username and password to log back in.',
    'settings_cancel': 'Cancel',
    'settings_confirm': 'Yes, log out',
    'settings_privacy_policy': 'Privacy Policy',
    'settings_contact_support': 'Contact Support',
    'settings_delete_account': 'Request Account Deletion',
    'settings_delete_account_desc':
        'Send a request to delete your account and all related data.',
    'settings_delete_account_confirm':
        'Request sent. We will contact you shortly.',
    'settings_theme': 'Theme',
    'settings_theme_light': 'Light',
    'settings_theme_dark': 'Dark',
    'settings_pin_code': 'PIN Code',
    'settings_pin_code_desc': 'Set a PIN code to unlock the app',
    'settings_biometric_login': 'Biometric Login',
    'settings_biometric_login_desc': 'Use Touch ID / Face ID for quick login',
    'lock_title': 'Enter PIN Code',
    'lock_subtitle': 'Enter your PIN to unlock the app',
    'lock_biometric': 'Touch ID / Face ID',
    'lock_biometric_reason': 'Authenticate to unlock the app',
    'lock_biometric_failed': 'Biometric failed. Enter PIN code',
    'lock_or': 'or',
    'settings_support_email': 'salievyt@gmail.com',
    'settings_support_chat': 'WhatsApp, Telegram',
    'settings_support_title': 'Contact Support',
    'settings_support_description': 'Choose your preferred contact method',
    'settings_privacy_note':
        'By pressing "Log Out" you end your current session.',

    
    'operations_title': 'Operations',
    'operations_create': 'Operation',
    'operations_empty': 'No operations',
    'operations_load': 'Load',
    'operations_today': 'Today',
    'operations_buys': 'Buys',
    'operations_sells': 'Sells',
    'operations_buy': 'Buy',
    'operations_sell': 'Sell',
    'operations_search': 'Search by number, client...',
    'operations_search_hint': 'Operation number, client name',
    'operations_filter_type': 'Type',
    'operations_filter_all': 'All',
    'operations_filter_period': 'Period',
    'operations_filter_period_today': 'Today',
    'operations_filter_period_week': 'Week',
    'operations_filter_period_month': 'Month',
    'operations_filter_period_all': 'All time',
    'operations_filter_sort': 'Sort',
    'operations_filter_period_custom': 'Custom period',
    'operations_filter_currency': 'Currency',
    'operations_filter_currency_all': 'All currencies',
    'operations_columns': 'View',
    'operations_columns_1': '1 column',
    'operations_columns_2': '2 columns',
    'operations_filter_date_from': 'From',
    'operations_filter_date_to': 'To',
    'operations_filter_date_apply': 'Apply',
    'operations_edit': 'Edit',
    'operations_save': 'Save',
    'operations_edit_title': 'Edit Operation',
    'operations_edit_success': 'Operation updated',
    'operations_rate': 'Exchange Rate',
    'operations_total': 'Total to Pay',
    'operations_amount': 'Currency Amount',
    'operations_filter_sort_newest': 'Newest',
    'operations_filter_sort_oldest': 'Oldest',
    'operations_filter_sort_amount_asc': 'Amount ↑',
    'operations_filter_sort_amount_desc': 'Amount ↓',
    'operations_clear_filters': 'Clear filters',
    'operations_found': 'Found:',

    
    'cash_title': 'Cash Register',
    'cash_balances': 'Balances',
    'cash_register_open': 'Shift Open',
    'cash_register_closed': 'Shift Closed',
    'cash_register_open_desc': 'Open the shift to start working',
    'cash_register_close': 'Close Shift',
    'cash_open_shift': 'Open Shift',
    'cash_transaction': 'Transaction',
    'cash_available': 'Available',
    'cash_reserved': 'Reserved',
    'cash_cashier': 'Cashier',
    'cash_opened_at': 'Opened at',
    'cash_no_data': 'No data',

    
    'currencies_title': 'Currencies',
    'currencies_buy': 'Buy',
    'currencies_sell': 'Sell',

    
    'analytics_title': 'Analytics',
    'analytics_no_data': 'No data to display',
    'analytics_no_data_desc':
        'Statistics will appear after performing operations',
    'analytics_overall': 'Overall Statistics',
    'analytics_operations_today': 'Operations today',
    'analytics_buys_sells': 'Buys / Sells',
    'analytics_turnover': 'Turnover (som)',
    'analytics_clients': 'Clients',
    'analytics_rates': 'Exchange Rates',
    'analytics_daily_chart': 'Operations by day',
    'analytics_popular_currencies': 'Popular Currencies',
    'analytics_profitability': 'Profitability (margin %)',
    'analytics_cashiers': 'Cashiers',
    'analytics_cash_balances': 'Cash Balances',
    'analytics_reports': 'Reports',

    
    'reports_title': 'Reports',
    'reports_subtitle': 'Download Reports',
    'reports_desc': 'Export data in CSV, Excel or PDF format with one click',
    'reports_daily': 'Daily Report',
    'reports_daily_desc': 'Daily summary: operations, turnover, balances',
    'reports_monthly': 'Monthly Report',
    'reports_monthly_desc': 'Monthly statistics by day',
    'reports_operations': 'Export Operations',
    'reports_operations_desc': 'All operations for the period in a table',
    'reports_cash': 'Export Cash',
    'reports_cash_desc': 'Cash flow movement',
    'reports_download': 'Download',
    'reports_generating': 'Generating report...',
    'reports_saved': 'File saved',
    'reports_saved_desc':
        'File is ready to use. Press "Share" to send or save it.',
    'reports_open_share': 'Share / Save',

    
    'general_retry': 'Retry',
    'general_refresh': 'Refresh',
    'general_loading': 'Loading...',
    'general_error': 'Error',
    'general_success': 'Success',
    'general_close': 'Close',
    'general_ops': 'ops.',
    'general_today': 'Today',
    'general_yesterday': 'Yesterday',
    'general_just_now': 'Just now',
    'general_min_ago': 'min. ago',
    'general_hours_ago': 'h. ago',
    'general_days_ago': 'd. ago',
    'general_som': 'som',
  };

  
  static const Map<String, String> _uz = {
    
    'app_name': 'My Exchange',
    'app_title': "Mening Ayirboshlash",

    
    'nav_operations': 'Operatsiyalar',
    'nav_cash': 'Kassa',
    'nav_currencies': 'Valyutalar',
    'nav_analytics': 'Analitika',
    'nav_settings': 'Profil',

    
    'login_title': 'Tizimga kirish',
    'login_username': 'Foydalanuvchi nomi',
    'login_password': 'Parol',
    'login_button': 'Kirish',
    'login_error': 'Kirish xatosi',
    'login_username_required': 'Foydalanuvchi nomini kiriting',
    'login_password_required': 'Parolni kiriting',
    'login_password_min': "Parol kamida 6 ta belgidan iborat bo'lishi kerak",
    'login_version': 'Versiya',
    'login_biometric': 'Touch ID / Face ID orqali kirish',
    'login_biometric_error': 'Biometrik autentifikatsiya mavjud emas',
    'login_biometric_failed': 'Biometriya orqali kirish muvaffaqiyatsiz',
    'login_biometric_save': 'Tez kirish uchun eslab qolish',
    'login_biometric_reason': 'Ilovaga kirish uchun shaxsingizni tasdiqlang',

    
    'settings_title': "Profil va sozlamalar",
    'settings_profile': 'Profil',
    'settings_user_info': "Foydalanuvchi ma'lumotlari",
    'settings_role': 'Lavozim',
    'settings_email': 'Email',
    'settings_phone': 'Telefon',
    'settings_language': 'Til',
    'settings_language_ru': 'Русский',
    'settings_language_kg': 'Кыргызча',
    'settings_language_en': 'English',
    'settings_language_uz': "O'zbekcha",
    'settings_language_uzCyrillic': 'Ўзбекча',
    'settings_app_version': 'Ilova versiyasi',
    'settings_logout': 'Chiqish',
    'settings_logout_confirm': 'Chiqishni xohlaysizmi?',
    'settings_logout_confirm_desc':
        "Qayta kirish uchun login va parol kerak bo'ladi.",
    'settings_cancel': 'Bekor qilish',
    'settings_confirm': 'Ha, chiqish',
    'settings_privacy_policy': 'Maxfiylik siyosati',
    'settings_contact_support': "Qo'llab-quvvatlash",
    'settings_delete_account': "Akkauntni o'chirish",
    'settings_delete_account_desc':
        "Akkauntingizni va barcha ma'lumotlarni o'chirish so'rovini yuborish.",
    'settings_delete_account_confirm':
        "So'rov yuborildi. Tez orada siz bilan bog'lanamiz.",
    'settings_theme': 'Mavzu',
    'settings_theme_light': "Yorug'",
    'settings_theme_dark': "Qorong'i",
    'settings_pin_code': 'PIN-kod',
    'settings_pin_code_desc': 'Ilovaga kirish uchun PIN-kod o\'rnatish',
    'settings_biometric_login': 'Biometrik kirish',
    'settings_biometric_login_desc':
        'Tez kirish uchun Touch ID / Face ID dan foydalanish',
    'lock_title': 'PIN-kodni kiriting',
    'lock_subtitle': 'Ilovani ochish uchun PIN-kodni kiriting',
    'lock_biometric': 'Touch ID / Face ID',
    'lock_biometric_reason': 'Ilovaga kirish uchun shaxsingizni tasdiqlang',
    'lock_biometric_failed': 'Biometriya xatosi. PIN-kodni kiriting',
    'lock_or': 'yoki',
    'settings_support_email': 'salievyt@gmail.com',
    'settings_support_chat': 'WhatsApp, Telegram',
    'settings_support_title': "Qo'llab-quvvatlash bilan bog'lanish",
    'settings_support_description': "Qulay aloqa usulini tanlang",
    'settings_privacy_note':
        '"Chiqish" tugmasini bosish orqali siz joriy seansni yakunlaysiz.',

    
    'operations_title': 'Operatsiyalar',
    'operations_create': 'Operatsiya',
    'operations_empty': "Operatsiyalar yo'q",
    'operations_load': 'Yuklash',
    'operations_today': 'Bugun',
    'operations_buys': 'Xaridlar',
    'operations_sells': 'Sotuvlar',
    'operations_buy': 'Xarid',
    'operations_sell': 'Sotuv',
    'operations_search': "Raqam, mijoz nomi bo'yicha qidirish...",
    'operations_search_hint': 'Operatsiya raqami, mijoz nomi',
    'operations_filter_type': 'Turi',
    'operations_filter_all': 'Barchasi',
    'operations_filter_period': 'Davr',
    'operations_filter_period_today': 'Bugun',
    'operations_filter_period_week': 'Hafta',
    'operations_filter_period_month': 'Oy',
    'operations_filter_period_all': 'Barcha vaqt',
    'operations_filter_sort': 'Saralash',
    'operations_filter_period_custom': "O'z davri",
    'operations_filter_currency': 'Valyuta',
    'operations_filter_currency_all': 'Barcha valyutalar',
    'operations_columns': 'Ustunlar',
    'operations_columns_1': '1 ustun',
    'operations_columns_2': '2 ustun',
    'operations_filter_date_from': 'Dan',
    'operations_filter_date_to': 'Gacha',
    'operations_filter_date_apply': "Qo'llash",
    'operations_edit': 'Tahrirlash',
    'operations_save': 'Saqlash',
    'operations_edit_title': 'Operatsiyani tahrirlash',
    'operations_edit_success': 'Operatsiya yangilandi',
    'operations_rate': 'Ayirboshlash kursi',
    'operations_total': 'Beriladigan umumiy summa',
    'operations_amount': 'Valyuta summasi',
    'operations_filter_sort_newest': 'Yangi',
    'operations_filter_sort_oldest': 'Eski',
    'operations_filter_sort_amount_asc': 'Summa ↑',
    'operations_filter_sort_amount_desc': 'Summa ↓',
    'operations_clear_filters': 'Filtrlarni tozalash',
    'operations_found': 'Topildi:',

    
    'cash_title': 'Kassa',
    'cash_balances': 'Qoldiqlar',
    'cash_register_open': 'Smena ochiq',
    'cash_register_closed': 'Smena ochiq emas',
    'cash_register_open_desc': 'Ishni boshlash uchun smenani oching',
    'cash_register_close': 'Smenani yopish',
    'cash_open_shift': 'Smenani ochish',
    'cash_transaction': 'Tranzaksiya',
    'cash_available': 'Mavjud',
    'cash_reserved': 'Zahiralangan',
    'cash_cashier': 'Kassir',
    'cash_opened_at': 'Ochilgan',
    'cash_no_data': "Ma'lumot yo'q",

    
    'currencies_title': 'Valyutalar',
    'currencies_buy': 'Xarid',
    'currencies_sell': 'Sotuv',

    
    'analytics_title': 'Analitika',
    'analytics_no_data': "Ko'rsatish uchun ma'lumot yo'q",
    'analytics_no_data_desc': "Operatsiyalardan so'ng statistika paydo bo'ladi",
    'analytics_overall': 'Umumiy statistika',
    'analytics_operations_today': 'Bugungi operatsiyalar',
    'analytics_buys_sells': 'Xaridlar / Sotuvlar',
    'analytics_turnover': "Aylanma (so'm)",
    'analytics_clients': 'Mijozlar',
    'analytics_rates': 'Valyuta kurslari',
    'analytics_daily_chart': "Kunlar bo'yicha operatsiyalar",
    'analytics_popular_currencies': 'Ommabop valyutalar',
    'analytics_profitability': 'Daromadlilik (marja %)',
    'analytics_cashiers': 'Kassirlar',
    'analytics_cash_balances': 'Kassadagi qoldiqlar',
    'analytics_reports': 'Hisobotlar',

    
    'reports_title': 'Hisobotlar',
    'reports_subtitle': 'Hisobotlarni yuklab olish',
    'reports_desc':
        "Ma'lumotlarni CSV, Excel yoki PDF formatida bir tugma bilan eksport qilish",
    'reports_daily': 'Kunlik hisobot',
    'reports_daily_desc': 'Kun yakuni: operatsiyalar, aylanma, qoldiqlar',
    'reports_monthly': 'Oylik hisobot',
    'reports_monthly_desc': "Oy ichidagi kunlar bo'yicha statistika",
    'reports_operations': 'Operatsiyalarni eksport qilish',
    'reports_operations_desc': 'Barcha operatsiyalar jadvalda',
    'reports_cash': 'Kassani eksport qilish',
    'reports_cash_desc': 'Kassadagi pul harakati',
    'reports_download': 'Yuklab olish',
    'reports_generating': 'Hisobot tayyorlanmoqda...',
    'reports_saved': 'Fayl saqlandi',
    'reports_saved_desc':
        'Fayl foydalanishga tayyor. Yuborish yoki saqlash uchun "Ulashish" tugmasini bosing.',
    'reports_open_share': 'Ulashish / Saqlash',

    
    'general_retry': 'Qayta urinish',
    'general_refresh': 'Yangilash',
    'general_loading': 'Yuklanmoqda...',
    'general_error': 'Xato',
    'general_success': 'Muvaffaqiyatli',
    'general_close': 'Yopish',
    'general_ops': 'op.',
    'general_today': 'Bugun',
    'general_yesterday': 'Kecha',
    'general_just_now': 'Hozirgina',
    'general_min_ago': 'daq. oldin',
    'general_hours_ago': 'soat. oldin',
    'general_days_ago': 'kun. oldin',
    'general_som': "so'm",
  };

  
  static const Map<String, String> _uzCyrillic = {
    
    'app_name': 'My Exchange',
    'app_title': 'Менинг Айирбошлаш',

    
    'nav_operations': 'Операциялар',
    'nav_cash': 'Касса',
    'nav_currencies': 'Валюталар',
    'nav_analytics': 'Аналитика',
    'nav_settings': 'Профиль',

    
    'login_title': 'Тизимга кириш',
    'login_username': 'Фойдаланувчи номи',
    'login_password': 'Парол',
    'login_button': 'Кириш',
    'login_error': 'Кириш хатоси',
    'login_username_required': 'Фойдаланувчи номини киритинг',
    'login_password_required': 'Паролни киритинг',
    'login_password_min': 'Парол камида 6 та белгидан иборат бўлиши керак',
    'login_version': 'Версия',
    'login_biometric': 'Touch ID / Face ID орқали кириш',
    'login_biometric_error': 'Биометрик аутентификация мавжуд эмас',
    'login_biometric_failed': 'Биометрия орқали кириш муваффақиятсиз',
    'login_biometric_save': 'Тез кириш учун эслаб қолиш',
    'login_biometric_reason': 'Иловага кириш учун шахсингизни тасдиқланг',

    
    'settings_title': 'Профиль ва созламалар',
    'settings_profile': 'Профиль',
    'settings_user_info': 'Фойдаланувчи маълумотлари',
    'settings_role': 'Лавозим',
    'settings_email': 'Email',
    'settings_phone': 'Телефон',
    'settings_language': 'Тил',
    'settings_language_ru': 'Русский',
    'settings_language_kg': 'Кыргызча',
    'settings_language_en': 'English',
    'settings_language_uz': "O'zbekcha",
    'settings_language_uzCyrillic': 'Ўзбекча',
    'settings_app_version': 'Илова версияси',
    'settings_logout': 'Чиқиш',
    'settings_logout_confirm': 'Чиқишни хохлайсизми?',
    'settings_logout_confirm_desc':
        'Қайта кириш учун логин ва парол керак бўлади.',
    'settings_cancel': 'Бекор қилиш',
    'settings_confirm': 'Ҳа, чиқиш',
    'settings_privacy_policy': 'Махфийлик сиёсати',
    'settings_contact_support': 'Қўллаб-қувватлаш',
    'settings_delete_account': 'Аккаунтни ўчириш',
    'settings_delete_account_desc':
        'Аккаунтингизни ва барча маълумотларни ўчириш сўровини юбориш.',
    'settings_delete_account_confirm':
        'Сўров юборилди. Тез орада сиз билан боғланамиз.',
    'settings_theme': 'Мавзу',
    'settings_theme_light': 'Ёруғ',
    'settings_theme_dark': 'Қоронғи',
    'settings_pin_code': 'PIN-код',
    'settings_pin_code_desc': 'Иловага кириш учун PIN-код ўрнатиш',
    'settings_biometric_login': 'Биометрик кириш',
    'settings_biometric_login_desc':
        'Тез кириш учун Touch ID / Face ID дан фойдаланиш',
    'lock_title': 'PIN-кодни киритинг',
    'lock_subtitle': 'Иловани очиш учун PIN-кодни киритинг',
    'lock_biometric': 'Touch ID / Face ID',
    'lock_biometric_reason': 'Иловага кириш учун шахсингизни тасдиқланг',
    'lock_biometric_failed': 'Биометрия хатоси. PIN-кодни киритинг',
    'lock_or': 'ёки',
    'settings_support_email': 'salievyt@gmail.com',
    'settings_support_chat': 'WhatsApp, Telegram',
    'settings_support_title': 'Қўллаб-қувватлаш билан боғланиш',
    'settings_support_description': 'Қулай алоқа усулини танланг',
    'settings_privacy_note':
        '«Чиқиш» тугмасини босиш орқали сиз жорий сеансни якунлайсиз.',

    
    'operations_title': 'Операциялар',
    'operations_create': 'Операция',
    'operations_empty': 'Операциялар йўқ',
    'operations_load': 'Юклаш',
    'operations_today': 'Бугун',
    'operations_buys': 'Харидлар',
    'operations_sells': 'Сотувлар',
    'operations_buy': 'Харид',
    'operations_sell': 'Сотув',
    'operations_search': 'Рақам, мижоз номи бўйича қидириш...',
    'operations_search_hint': 'Операция рақами, мижоз номи',
    'operations_filter_type': 'Тури',
    'operations_filter_all': 'Барчаси',
    'operations_filter_period': 'Давр',
    'operations_filter_period_today': 'Бугун',
    'operations_filter_period_week': 'Ҳафта',
    'operations_filter_period_month': 'Ой',
    'operations_filter_period_all': 'Барча вақт',
    'operations_filter_sort': 'Саралаш',
    'operations_filter_period_custom': 'Ўз даври',
    'operations_filter_currency': 'Валюта',
    'operations_filter_currency_all': 'Барча валюталар',
    'operations_columns': 'Устунлар',
    'operations_columns_1': '1 устун',
    'operations_columns_2': '2 устун',
    'operations_filter_date_from': 'Дан',
    'operations_filter_date_to': 'Гача',
    'operations_filter_date_apply': 'Қўллаш',
    'operations_edit': 'Таҳрирлаш',
    'operations_save': 'Сақлаш',
    'operations_edit_title': 'Операцияни таҳрирлаш',
    'operations_edit_success': 'Операция янгиланди',
    'operations_rate': 'Айирбошлаш курси',
    'operations_total': 'Бериладиган умумий сумма',
    'operations_amount': 'Валюта суммаси',
    'operations_filter_sort_newest': 'Янги',
    'operations_filter_sort_oldest': 'Эски',
    'operations_filter_sort_amount_asc': 'Сумма ↑',
    'operations_filter_sort_amount_desc': 'Сумма ↓',
    'operations_clear_filters': 'Фильтрларни тозалаш',
    'operations_found': 'Топилди:',

    
    'cash_title': 'Касса',
    'cash_balances': 'Қолдиқлар',
    'cash_register_open': 'Смена очик',
    'cash_register_closed': 'Смена очик эмас',
    'cash_register_open_desc': 'Ишни бошлаш учун сменани очинг',
    'cash_register_close': 'Сменани ёпиш',
    'cash_open_shift': 'Сменани очиш',
    'cash_transaction': 'Транзакция',
    'cash_available': 'Мавжуд',
    'cash_reserved': 'Заҳираланган',
    'cash_cashier': 'Кассир',
    'cash_opened_at': 'Очилган',
    'cash_no_data': 'Маълумот йўқ',

    
    'currencies_title': 'Валюталар',
    'currencies_buy': 'Харид',
    'currencies_sell': 'Сотув',

    
    'analytics_title': 'Аналитика',
    'analytics_no_data': 'Кўрсатиш учун маълумот йўқ',
    'analytics_no_data_desc': 'Операциялардан сўнг статистика пайдо бўлади',
    'analytics_overall': 'Умумий статистика',
    'analytics_operations_today': 'Бугунги операциялар',
    'analytics_buys_sells': 'Харидлар / Сотувлар',
    'analytics_turnover': 'Айланма (сўм)',
    'analytics_clients': 'Мижозлар',
    'analytics_rates': 'Валюта курслари',
    'analytics_daily_chart': 'Кунлар бўйича операциялар',
    'analytics_popular_currencies': 'Оммабоп валюталар',
    'analytics_profitability': 'Даромадлилик (маржа %)',
    'analytics_cashiers': 'Кассирлар',
    'analytics_cash_balances': 'Кассадаги қолдиқлар',
    'analytics_reports': 'Ҳисоботлар',

    
    'reports_title': 'Ҳисоботлар',
    'reports_subtitle': 'Ҳисоботларни юклаб олиш',
    'reports_desc':
        'Маълумотларни CSV, Excel ёки PDF форматида бир тугма билан экспорт қилиш',
    'reports_daily': 'Кунлик ҳисобот',
    'reports_daily_desc': 'Кун якуни: операциялар, айланма, қолдиқлар',
    'reports_monthly': 'Ойлик ҳисобот',
    'reports_monthly_desc': 'Ой ичидаги кунлар бўйича статистика',
    'reports_operations': 'Операцияларни экспорт қилиш',
    'reports_operations_desc': 'Барча операциялар жадвалда',
    'reports_cash': 'Кассани экспорт қилиш',
    'reports_cash_desc': 'Кассадаги пул ҳаракати',
    'reports_download': 'Юклаб олиш',
    'reports_generating': 'Ҳисобот тайёрланмоқда...',
    'reports_saved': 'Файл сақланди',
    'reports_saved_desc':
        'Файл фойдаланишга тайёр. Юбориш ёки сақлаш учун «Улашиш» тугмасини босинг.',
    'reports_open_share': 'Улашиш / Сақлаш',

    
    'general_retry': 'Қайта уриниш',
    'general_refresh': 'Янгилаш',
    'general_loading': 'Юкланмоқда...',
    'general_error': 'Хато',
    'general_success': 'Муваффақиятли',
    'general_close': 'Ёпиш',
    'general_ops': 'оп.',
    'general_today': 'Бугун',
    'general_yesterday': 'Кеча',
    'general_just_now': 'Ҳозиргина',
    'general_min_ago': 'дақ. олдин',
    'general_hours_ago': 'соат. олдин',
    'general_days_ago': 'кун. олдин',
    'general_som': 'сўм',
  };
}
