"""
Generated by Django 5.0.1 — add city field to RegistrationRequest.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='city',
            field=models.CharField(
                blank=True,
                choices=[
                    ('bishkek', 'Бишкек'),
                    ('osh', 'Ош'),
                    ('jalal-abad', 'Джалал-Абад'),
                    ('karakol', 'Каракол'),
                    ('naryn', 'Нарын'),
                    ('talas', 'Талас'),
                    ('batken', 'Баткен'),
                    ('tokmok', 'Токмок'),
                    ('kyzyl-kiya', 'Кызыл-Кия'),
                    ('balykchy', 'Балыкчы'),
                    ('kant', 'Кант'),
                    ('kara-balta', 'Кара-Балта'),
                    ('mailuu-suu', 'Майлуу-Суу'),
                    ('tash-kumyr', 'Таш-Кумыр'),
                    ('kerben', 'Кербен'),
                    ('isfana', 'Исфана'),
                    ('nookat', 'Ноокат'),
                    ('sulukta', 'Сулюкта'),
                    ('cholpon-ata', 'Чолпон-Ата'),
                    ('kochkor-ata', 'Кочкор-Ата'),
                ],
                max_length=50,
                verbose_name='Город',
            ),
        ),
    ]
