# Generated by Django 5.0.1 on 2026-06-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Остаток')),
                ('reserved', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Зарезервировано')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Кассовый остаток',
                'verbose_name_plural': 'Кассовые остатки',
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Открыта в')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта в')),
                ('is_open', models.BooleanField(default=True, verbose_name='Открыта')),
                ('opening_balance', models.TextField(blank=True, help_text='JSON с начальными остатками по валютам')),
                ('closing_balance', models.TextField(blank=True, help_text='JSON с конечными остатками по валютам')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Кассовая смена',
                'verbose_name_plural': 'Кассовые смены',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Внесение наличности'), ('withdrawal', 'Выдача наличности'), ('inkassation', 'Инкассация')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Остаток до')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Остаток после')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Кассовая операция',
                'verbose_name_plural': 'Кассовые операции',
                'ordering': ['-created_at'],
            },
        ),
    ]
