# Generated by Django 5.0.1 on 2026-06-16 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbalance',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_balance', to='currencies.currency', verbose_name='Валюта'),
        ),
    ]
