# Generated by Django 5.0.1 on 2026-06-16 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0002_initial'),
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='Кассир'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Кассир'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transactions', to='currencies.currency', verbose_name='Валюта'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['-created_at'], name='cash_cashtr_created_5d4d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['cashier', '-created_at'], name='cash_cashtr_cashier_4be862_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['currency', '-created_at'], name='cash_cashtr_currenc_be1701_idx'),
        ),
    ]
