# Generated by Django 6.0.6 on 2026-06-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbalance',
            options={'ordering': ['currency__code'], 'verbose_name': 'Кассовый остаток', 'verbose_name_plural': 'Кассовые остатки'},
        ),
    ]
